PathOfBuildingCommunity/PathOfBuilding-PoE2

src/Modules/CalcBreakdown.lua
src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/378
Offensive penetration wasn't properly handling cases when resistance was less than 0 before penetration.
Also updated defensive penetration calculations.
- Load the provided build
- Observe correct damage multipliers for damage taken and damage dealt
https://pobb.in/YMNosS6UIvf3

Fix penetration calculations

---

src/Modules/ModParser.lua

- 20% increased Armour if you've consumed an Endurance Charge Recently
- 20% increased Critical Damage Bonus if you've consumed a Power Charge Recently
- 20% increased Energy Shield if you've consumed a Power Charge Recently
- 20% increased Evasion Rating if you've consumed a Frenzy Charge Recently
- 50% increased Evasion Rating if you've consumed a Frenzy Charge Recently

Add support for Charge consumed recently tree nodes

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/375
Archmage mana cost wasn't scaled by modifiers to mana cost.
https://pobb.in/-8oxpiDVcsL8

Fix Archmage mana cost

---

src/Classes/ModStore.lua

Fixes #379.
Scaling modifiers that affect levels of skill gems should be floored instead of rounded.
Check #379 for more details.

Fix Scaling of +Levels to Skill Modifiers

---

src/Launch.lua

Lua side code for https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/65
Changes the hotkey from just (print screen) to (control + print screen) in an attempt to prevent potential conflicts with other screen capture programs.

Implement lua side hotkey for screenshots

---

src/Classes/PassiveSpec.lua
src/Classes/PassiveTreeView.lua
src/Modules/CalcSetup.lua

Fixes #402 
When you allocate a node in a weaponSet, a conditional mod is added so we can calculate the correct nodes based on which Set is active. The problem is this mod is only ever added or updated and never removed for instances of Normal/Non-WS allocation.  So once allocated in either set, it will permanently have the mod which excludes it from being a Normal node that should apply regardless of WS. In other words, that node is permanently either a WS1 or WS2 node in the background, even if allocated as Normal.
So yeah we're fixing that.
- Import build
- Allocate Ingenuity as WS2
- Deallocate and allocate as Normal
- Verify Intelligence increases while in WS1
---
- Import build
- Allocate Ingenuity as WS1
- Activate WP2
- Deallocate and allocate as Normal
- Verify Intelligence …

Fix passive nodes being permanently attached to a Weapon Set

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Partially Fixes #180 .
Support for Buff Expiry Rate to Chronomancer
- In-Game tree with the same nodes , correctly shows 10 seconds
```
eNrdHGtT40by8_pXTLnqrnJ1BvS0JQ6SMgYWElhYG3az-UIN0thWkDWONOKRVP77dc9IsmwsWWY3d1e3VIGs6e7p90xPj_fgh-dZSB5ZnAQ8Omzru1qbsMjjfhBNDtu3N6c7TvuH71sH11RMr8ZHaRDiiPF9692B_EBC9shCQNQA0QtpknygM3bYHvHYYzFLkjahiccif7AYG0xjHvEZjQCiTQSNJ0x8yjnQ7nQgNKUx9QSLL5B6PxX8kvuAOaZhwtpkRoNoxL0HJt7HPJ0fts02eQzYkwI6v7y-Gt60gcV3B9chfWHxSFBBEvh12O6DqHTCzgIBKDRMAd60dw2nvVcLf5TGiTimM3hshjeaM-YXoPqu6fTsKtjrmJ2Mx8wTwSMbxIEYTFE1C2SjCnFr4Ms0FME8DFDvGUIl_Nlr2mDjCuAbLmh4fD0qYC1n17X1enC-sEEl4c-BmB6FoMvmxM8nUSBYGd7YNd1et26K1zg22MxyapGueZDwaHupm7M2SMMQwq2MUKmpIUtY_EhFsMxSJfyAz-6DaFmxG4S-pBEd8ESUPKIO9JpBDojEEsYmhBHzOCSLpUnM3ZrgKU20Hr1yxotgzJpDbiVMhrAtN2-T42TUFG5rwm9jaAhZshnkiKdhQ0ixSFm9ypx1zJ4XUJX5 …
```

add support for Buff Expiry Rate

---

src/Classes/TreeTab.lua

At the moment, you can change the values ​​for heatmap calculation to {5, 10, 15, all}. In some cases, this is inconvenient. Sometimes you want to search up to 4 or 6 or 20, etc.
I added a new value "Custom". By selecting it, a new EditControl appears, in which you can enter any value.

Added the ability to custom change max node depth for heat map

---

src/Classes/CheckBoxControl.lua
src/Classes/ItemsTab.lua
src/Classes/NotableDBControl.lua

This lets users select which emotions they have available to restrict the list of anoints.
I'd appreciate if someone could check that I'm getting the emotion icon images the correct way (via `main:LoadTree`, then accessing via `tree.ddsMap` directly).
The images are displayed by modifying the `CheckBoxControl` class to have a `checkImage` field that overrides the display.  I took some liberties with the display, giving enabled controls a white outline to make it clearer when a control is selected/not selected without making it excessively difficult to see the image.
I slightly refactored the `NotableDBControl` class so that the filtering controls are included in the `rect` for the control, as opposed to technically appearing outside of it (which was weird and required offsets in the code …

Add Emotion filtering to Anoint popup

---

src/Data/ModCache.lua
src/Modules/CalcDefence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

These changes allow the calculation and display of negative unreserved spirit and the warning associated with it. it also adds a line in the calcs panel in this scenario that shows where the override is coming from.
The linked build also has negative life and mana custom modifiers to make sure the life/mana reservation code is unnaffected in those cases.
https://pobb.in/kglYQAEZMgvn

improve implementation of Kaom's Heart 'You have no spirit' mod.

---

src/Classes/TreeTab.lua
src/Modules/CalcSetup.lua
src/Modules/ModParser.lua

There are Time-Lost jewel mods that can already be on the nodes in the radius of the jewel, and these are being added as a separate line. This PR combines them and fixes the issue of unallocated nodes in the radius not updating immediately.
<pre>eNqlW1tv27gSfq5_BWHgALs4TqKrL0GyC8d2LgdJ6tpJu7svBSPTNje05EpUEnex__0MSUmWL5KppA-tLM43MxzODIcj9uz3twVDLySMaOCf181jo46I7wUT6s_O648Pl0ft-u-_1c6GmM8_Ty9iysSI9Vvt05n8gRh5Iey8brXqyGM4iu7xgpzXR9ifkbCOcOQRf9JbD9wHPqkjjsMZ4V9TqcZ3E9BzHGKPk_BWcOzGPLgLJoDgYQyIBab-OPCeCb8Kg3gJmtbRCyWviubmbvh59FAHrT6dDRlekXDMMUcR_HVe78Ls8IxcUw4QzGKgN-onpbQXcRjxPl7A42HMeEnI5DBZL6T8LmacLhkVpknorSJ60Lc3x7631sA0Cpk_BByz_nB8WA1FGWjY4hvl8wsGc9PiK6hvZj7lRJt8GNAo8CtprUXcixkDJ9WiHZGIhC-YU01FesHiifqaNrnDPu4FEdejHJIQgoVXAoyJF0B8VZVREXlLp0SfstI8EkBVbd43j8FYl64y4_cpNIIEo0c5DmKmScnXycW0CtNLn7 …

Add support for merging mods on nodes in radius of Time-Lost jewels

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

implemented support for 'Into the Breach' and 'Lucid Dreaming'

---

src/Modules/Data.lua

Mods of type "LIST" containing other mods like
```lua
mod("MinionModifier", "LIST", { mod = mod("DamageTaken", "MORE", nil) }),
```
and originating from (support?) gems weren't properly propagating their source to the inner mod which resulted in errors when viewing breakdowns.
https://pobb.in/hmHfkHNk0PP_

Fix crash when hovering over breakdown for Minion skills

---

src/Modules/CalcTools.lua

The minion skills take the actor level of the minion when there is only 1 entry in the levels table with a stat interpolation value

Fix Minion Spell skills doing 0 damage

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_dex.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/sup_dex.txt
src/Export/Skills/sup_int.txt

This commit also makes Innervate work similarly to Ice Bite in terms of how the stat map is written.
Fixes #507 .
When adding the support gem `Ice Bite` to one skill, the 35% Cold Damage Gained is applied regardless of whether an enemy has been frozen recently or not.
- Check mod and damage gained
https://maxroll.gg/poe2/pob/uvfcq0y9

Make Ice Bite work as intended

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Port the Lightning Conduit Mod from POB for POE1
https://pobb.in/8gNhxMRJ7QWU

Add Lightning Conduit Shock Mod

---

src/Modules/ModParser.lua

Adds Scouring Wind mod support for Stormweaver (called it Elementalist in my commit... Oops.)
https://pobb.in/8gNhxMRJ7QWU

Add Stormweaver Scouring Winds mod Support

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

fix 'Presence Present' notable and similar small nodes that use 'while you have an ally in your presence'
https://pobb.in/DioT_ukny7VJ

fix 'Presence Present' notable and similar small nodes

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes parsing the tree mods below:
12% increased Grenade Damage
12% increased Grenade Area Of Effect
15% increased Cooldown Recovery Rate for Grenade Skills
grenade fuse mods still not supported.
https://pobb.in/gU6KXGUNj27j

add support for parsing grenade dmg, aoe and cdr mods

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Cannot use charms modifier is currently not supported
- Equip A belt with +2 Charm Slots; Amethyst Charm; Ruby Charm; Sapphire Charm
- Allocate Oasis keystone
- Verify that bonuses from charms no longer affect the player
```
eNq9W1tz4joSfp78ChevmwnmGpIic4oAmaQ2Fw4kMztPU4otQBthsbachLO1_327JdsYgoxMtnYeZmzcX9-kbnW3Pd0_3hfceaVhxERwUamduBWHBp7wWTC7qDw9Xn3tVP74dtQdETl_mF7GjOOT-rejL11143D6SjkA6xXH4ySK7smCXlTGJJjRsOKQyKOB318_uBcBrTiShDMqf6RS3d81QM9JSDxJw1vk2IuluBM-IGQYA2JBWDAR3guV30MRL0FgxXll9E3T3NyNHsaPFdDqS3fEyYqGE0mkE8FfF5UeWEdmdEAW8DegCI8B4p647WalWgi5jMNIlsFNlpT6GWntpG4iHIV0OJ1ST7JX2g-Z7M9J4OWEmHBlae9iLtmSM1yLhN6o0_UH1rW2ifZRSMIHo0neLaftTjG5kPuV_snk_JKDF-2ZI-RmFjBJy2FGgkUiKG_EBsLo_JhzCBQr2jGNaPhKJNvSxshbLJ5ZUMZFdyQgfRFZ-B8pRzSEqJWlABPqCQj0sjJKIm_ZlNpTlrIjAZTV5jA7hhNbutKMD1NoDCnOjnIiYm5JKddJp2X …
```

Add support for Oasis keystone

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Implement Charge Infusion skill.
- Verify on build.
https://maxroll.gg/poe2/pob/xxhu705b

Implement Charge Infusion

---

src/Modules/ConfigOptions.lua

Fixes # .
- When first encountering this config I was confused as to why it wasn't set in whole meters, this clarifies it.

Add tooltip to clarify distance to enemy units

---

src/Data/Uniques/boots.lua
src/Export/Uniques/boots.lua
src/Modules/ItemTools.lua

Fixes #112 .
Extra lightning removed (already included in _current_ variant).
Unique movement speed mod now shows correctly after improving the regex to hide 0-value modifiers.
- Tested on POB2
- All tests successful
- Checked on [trade](https://www.pathofexile.com/trade2/search/poe2/Standard/EDQkZ3RT5)
https://pobb.in/EBYaDilf3RIp

Fix Gamblesprint missing movement speed mod 

---

src/Modules/ItemTools.lua

These weren't applying to 2 decimals like the should for flasks gain charges. This also removes a redundant round

Fix numbers not showing to correct decimal places in some UI modLines

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

Fixes #532 .
We were using the wrong modifier on the stat
- Tested with the build below
```bash
eNqlW1132jgTvu7-Ch-uafAHYNhDdg-BpKGbNCwk7e570yNsAdrIFrXlJPTXvyPJNoYiY5O9SI01z8xoRjPSjLyDP98CarzgKCYsvGxYF2bDwKHHfBKuLhtPjzcfe40___htMEV8_bC8SggVI_Yfv30YyB8GxS-YXjZsu2F4FMXxFxTgy8Y3FEWERQ0DxR4O_dHeyCICFhgGOYpWmH_NhJvfLWCyRhHyOI7uBONhwtk98wHHowQ3jACRcM68Z8w_RSzZgMIN44XgV0UzuZ8-zB4boNyHwZSiLY7mHHEjhj-XjSFMEq3wLeEAQTQBeqvfveg0WqX0V0kU8zEK4LEabr7B2M9JzQvLbrum07N7bdPtODoUmMWLtiMU80cS4ALc6bhW2-6pv10dfBrh6-USe5y84FFE-GiNQq_ARoerS3ufUE42lAjvpfS2jv72F9aWqWX-yDii4-l8x7Z90THbjmnbPdvslcMYP639N8LXQFhfxIhFUbLhsGSvKGP-HoN-mbQrCguhvjwBnaxCwvF52CkjMQvPN2W1CY4SSsEkRWKt6Wc4xtEL4mRfLf1CY8GChPu26zjVfMWoz17DHNa7MC3tHIYRRg9LFTcz5JMkvsc8wnGOdi60ku5RiEYsLuQSs19GO8URJEK-BzFPAObYY5A796SAGfq2a7l2v9u2rQoSj_PRir4jS1ydstasUkBd …
```

Fix Corrupting cry using reduced effect instead of less

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_int.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/act_int.txt
src/Export/Skills/sup_int.txt
src/Modules/CalcOffence.lua

Currently DD's corpse explosion mod is to supported 
Double check to make sure physical dmg is being scaled properly by the passive tree

Add support for Deatonate Dead Corpse explosion calculation

---

src/Data/ModCache.lua
src/Data/Skills/act_int.lua
src/Data/Skills/sup_dex.lua
src/Data/Skills/sup_str.lua
src/Export/Skills/act_int.txt
src/Export/Skills/sup_dex.txt
src/Export/Skills/sup_str.txt
src/Modules/CalcActiveSkill.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

This allow supports (or possibly other sources) to add mods to empowering skills.
This is different from normal mod transfer from support to active skill because the support doesn't know the conditions and flags of the active skill's "GlobalEffect".
Copying tags from the "Empowered" flag on an active skill to support skill mods enables them to be merged into one buff.
I'm not sure if this hacky solution is the best. We may come up with better system when implementing warcries. We may even be able to get rid of the config switch when all empowering effects are properly accounted for.
https://pobb.in/jKr8dJPlXHOI

Add support for additional empowering effects

---

src/Modules/Common.lua

Switch formula from m_floor to floorSymmetric for corrupted unique rolls

Fix Corrupted Unique roll ranges formula

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #544 .
Add Threaded Light Woven Focus spell dmg per 10 spirit request.
Also added _"per (%d+) spirit"_ for future reference.
- Tested on POB2
- Automatic tests successful
https://pobb.in/6NwRXbHnSHEh

Add Threaded Light Woven Focus spell dmg per 10 spirit

---

src/Classes/PassiveSpec.lua

Fixes a possible crash (#575) when a node `allocMode` is set to `nil`, which breaks generating the modlist in `CalcSetup.lua`
Fixes #575  .
When multiple choice passives are deallocated, `allocMode` was being set to `nil`, which breaks how modlists are generated for weapon sets in [CalcSetup.lua:310](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/blob/ac80996c3a0e70387e98e125bd16c9f7f8be0baa/src/Modules/CalcSetup.lua#L310).
- Select Ranger, Deadeye ascendency in passive tree configuration. Allocate `Projectile Proximity Specialization` and one of `Far Shot` or `Point Blank`. Hover over the other.
- Use devAltMode to verify that the nodes have `allocMode=0`
- Code in `DeallocSingleNode` performs the same changes to the node data as the deleted lines in this change (and …

Fix Crash when switching between multiple choice Ascendancies

---

src/Classes/ItemsTab.lua

Adds the keybind to quickly import items into PoB without needing to confirm each time. You can also press enter now to confirm selection

Add Shift + Ctrl + V to bypass item import confirmation box

---

src/Classes/SkillsTab.lua

Fixes #611 . Took a shot at it myself, first time working here so unsure if this is the way to do it properly, let me know if there's a better way. I tested the changes on my local with different setups, seems to work fine.
Just added two conditionals to check if the socket group is enabled ([L1303](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/612/files#diff-59529d6b10ff730a86299280a8a431ddac44ef9ef63592a48dbe2d45c1547f89R1303)), or if the single gem instance is enabled ([L1308](https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/pull/612/files#diff-59529d6b10ff730a86299280a8a431ddac44ef9ef63592a48dbe2d45c1547f89R1308)), before counting it
- Using the POB code in the issue I recreated the scenario and it doesn't show the warning anymore.
```shell …
```

Fix support gem counting when not enabled

---

src/Classes/TradeQueryGenerator.lua
src/Data/QueryMods.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/588
A couple types were incorrectly tagged and armours were missing applicable tags sometimes e.g. type specific ones there were also a couple case of internal tags in a base type block some appearing in queryMods.lua
This works by generating all combination an item base category can have and then iterating over these to check if a given mod is present in the category. This correctly handles black lists inside an item base category. Filtering is also done to remove some fluff from the generated table tags to hopefully speed up calculations and make it a little clearer.

Fix missing trade tags on certain items resulting in them not being generated.

---

spec/System/TestDefence_spec.lua
src/Modules/CalcDefence.lua
src/Modules/Data.lua

Closes #542
Closes #451
A previous fix for MoM EHP calculations was erroneous.
- Check that EHP stops changing when adding mana past MoM limit
- Check that EHP scales linearly when only adding more to the hit pool

Improve EHP accuracy

---

src/Modules/ItemTools.lua

Ventor's stats weren't showing and would disappear resulting it the list getting corrupted and crashing. This was introduced in the proper scalability PR and resulted in signs not being presented on 0 values causing mod parser to fail resulting in them being hidden, this changes it such that the + sign is used for 0 values like it did previously.

Fix item range crash on ventor's gamble

---

src/Classes/ItemsTab.lua

Fixes #638 
Increased flask charges gained is not taken into account when calculating flask uptime
- Import build code from the issue
- Verify that life flask uptime is now 100%
Use the build code from the issue

Fix total flask charges gained in flask uptime calculation

---

Dockerfile
src/Classes/EditControl.lua
src/Modules/Common.lua
src/UpdateCheck.lua

In https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/59 there were significant foundational improvements for users installing Path of Building into paths with characters that cannot be expressed in their codepage.
There is also a companion PR for the Launcher in https://github.com/PathOfBuildingCommunity/PathOfBuilding-Launcher/pull/6.
In short:
* the LuaJIT runtime is patched to understand paths in UTF-8,
* API functionality like FileSearch yields paths encoded in UTF-8,
* `GetScriptPath`/`GetUserPath` yields paths in UTF-8,
* text rendering draws glyphs that don't exist in the fonts as `[U+1234]` "tofu" in a smaller font size,
* mouse selection understands codepoint boundaries,
* a compiled extension `lua-utf8` is exposed to the Lua side.
This means that Lua …

Fix fallout from SimpleGraphic upgrade with wider Unicode support

---

src/Classes/SkillsTab.lua

Don't add stat comparisons for hovered gem quality if gem has no quality stats

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Fixes # .
The code for "Dead can Dance" was adding 5 accuracy directlly to minions per dex, instead of adding the dex to the minion. I feel it would be better to add to the minions Dex for clarity. It would be easy for a player to allocate the node, notice there is no Dexterity change in the minion, and then create an issue.
Also the possibility of further mods affecting minion attributes.
-Accuracy value added is the same after Dex is calculated for minion.
-
-

Dexterity added to Minions instead of accuracy

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #573
Number of times Stunned Recently implemented. Briny Carapace uses this, and Quick Recovery probably does? I assume it stacks, I haven't touched that anyway yet. Also changed warcries used recently to clean up config.
EDIT: ooooooh cant use the # sign at the start of a sentence, thats why my text was all wonky.
Short form
- Times Stunned Recently is hidden unless Stunned Recently is toggled on
- Same for # Warcries used Recently
- The default value in each number box is 1, it is guaranteed the player used at least 1 warcry if toggled
- This also fixes the issue of toggling warcries, but not having any damage increase from "Deafening Cries" unless you manually enter a value into the box.
- When unchecking "Stunned Recently", the # times box will go red, and the values inside the …

Added Times Stunned Recently and edited Warcries used Recently

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes # .
-Added support for Dance with Death. It checks for empty offhand, and a one handed weapon.
-Added config for using charm, and made "Lucky Rabbit Foot" work.
-"increased effect of charms applied to you", "flask and charm charges gained", and "while you have an active charm" were added. Some nodes that used this were "Lucky Rabbit Foot" and "Efficient Alchemy"
-Tested Dance with Death with equipment pairs to ensure it worked as expected. Equipping anything in slot 2 is recognized as failing the check. Using a two hand melee fails. Using a bow with slot 2 open fails. Using a wand with slot 2 open fails. Using a mace and an empty slot 2 passes as the node activates.
-Resistance from Charm increased with charm effect. I copied the flask code, so it should only work on the player. …

Add support for Dance with Death and Charm mods

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
- Blackgleam
- Asphyxia's Wrath
- Beyond Reach
These quivers all have "Attacks gain % of damage as extra [type] damage"
It only checks for the Attack flag. So it does apply to concoctions as well. I assume this is right, but I do not have a Ranger to test. If someone could confirm that would be great!
-
-
-

Added Support for Attacks Gain Extra mods on Quivers

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
The unique chest Apron of Emiran has "50% reduced bleeding duration on you". We were only looking for bleed duration, not bleeding duration. 
-
-
-

Added support for Reduced Bleeding Duration on you

---

src/Data/ModCache.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Fixes # .
Svallin unique shield has the mod "Block chance is lucky", which is simply different wording from poe1. I removed a few lines regarding spell block, but kept some others for future reference.
Also removed the spell block percent on the Damage Avoidance tab. So it no longer shows e.g. 35%/0% with the 0% being spell block.
-
-
-

Added support for Svalinn lucky block

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
Sanguine Diviner unique wand has "25% of spell mana cost converted to life cost". Old code looked for slightly different wording, and applied to all skills. This specifically applies to only spells.
-Tested in game that it does not apply to warcries, as I wasn't totally sure. Confirmed it doesn't.
https://maxroll.gg/poe2/pob/jm4gl0zs

Added support for 25% of spell mana cost converted to life cost

---

src/Data/ModCache.lua
src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Fixes # .
Two mods on Skin of the Loyal unique chest now work. "energy shield is increased by overcapped cold resistance" and "evasion rating is increased by overcapped lightning resistance".
-
-
https://maxroll.gg/poe2/pob/xf4g60ft

Added support for Skin of the Loyal overcap mods

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

The unique body armour Irongrasp had both mods, "Iron Will" and "Iron Grip". This PR adds both to the keystone area in modparser.lua as poe2db has them in the keystone family still.
- Equipped a bow to ensure Iron Will only applies to spells.
- Iron Grip applies to spells and not attacks.
- NoStrBonusToLife flag set. As both Iron Will and Iron Grip make strength provide no bonus to life.
https://maxroll.gg/poe2/pob/g45c30fo

Added support for Iron Will and Iron Grip

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
The unique gloves Idle Hands have a mod "25% increased attack speed while on full mana". This line makes it work.
-
-
-
https://maxroll.gg/poe2/pob/vu5f80fx

Added support for Attack Speed when on full mana

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #180 
- Implement Quicksand Hourglass from Chrono
```
eNqlWt1z2roSf-75Kzx-bsNHIKRnoGcISZrMJA2FpL33qSNsAbqRLWrLSTh__d2VZGMoMjLpQ2qs_e2XtKvdhf4_bxH3XmiSMhEP_NZJ0_doHIiQxYuB__R4_enc_-fLX_0xkcuH-UXGOK60v_z1oa8-eJy-UA5A3ws4SdNvJKIDfyqSgCY0TX2PpAGNw9FmbbRMRCwiEgOF70mSLKj8kctv_kJGS5KQQNLkDnkPMynuRQhImWTU9yLC4qkInqn8mohspUS_MPqqaW7vxw-TRx_0-9Afc7KmyVQS6aXwZ-APwU6yoDdMAoTwDOjPuidnvXbXb1QiLrIklZckgkdX5HRFaVgQt0_a7fNur9XRf22gcUKv5nMaSPZCRwmToyW6qeDy2YarS3ufcclWnOEO5Bra6G_-YN1qNm3Ej0ISfjmebmg7Zyen3a6x_awaJzb7YpXwk8nlBQffHiEFsbeLmEl6JHgsWCrid9hXhlpNHGWcQ5A50U5oSpMXItm2WnbeIpqx-Cjv3ZOYjERaip1OFemYQg6I5RaieQAwpYGAZFGGgEonZ5vYcZC4n49V9B2bU3fKWlYZQF1tjrPjaupKV5vxcQpNIFu6UU5Fxh0p5SZjWc_CJX07THQbl85Y1x5ev8uE7WbXLvRFYBQetkHlgqubcUHZbZ2cn3VPe-etXrP52SphvFynLCD8nryxKIsgLz-SZ7oReNazH6rFUsaQUmzQzrkNes0SWh81 …
```

Implement Quicksand Hourglass

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Fixes #331 .
Heavy Notable passive tree skill notable wasn't supported yet. Now it's implemented and adds strength requirements from equipped items to armour.
- imported build from the game to PoB
- compared value calculated by game and PoB
https://maxroll.gg/poe2/pob/z34yd0y5

Add support for Heavy Armour notable

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Fixes # .
Burden of Shadows unique staff has a mod "Skills gain 1% of Damage as Chaos Damage per 3 Life Cost". Adding this line makes it work.
- Checked calculations for a few skills. Using the build below.
- Fireball has a life cost of 118. 118/3 is 39.33, so its rounded down to 39.
- The base total fire damage for Fireball in the build is 212 - 319.
- 212*0.39 is 82.68, Which is rounded up to 83 for the minimum chaos damage.
- 319*0.39 is 124.41, round to 124, which is the max chaos added.
https://maxroll.gg/poe2/pob/hi7c70yf

Add support for Burden of Shadows 1% inc Chaos damage per 3 Life cost

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
Infinite Pursuit unique boots have a mod "25% increased movement speed while affected by an ailment" This checks for all 6 current ailments.
-
-
-

Add support for increased Movement Speed while affected by an Ailment

---

spec/System/TestDefence_spec.lua
src/Modules/CalcDefence.lua

#552 introduced a bug <sup>(who could've done such a thing?)</sup> where ES bypass + MoM did not work because code was relying on "EnergyShieldProtectsMana" flag which is not set to true by default in pob2 (should it?)
Added some tests which should prevent this happening again in the future

Fix ES bypass regression from #552

---

src/Modules/Build.lua

Fixes # .
The dropdown box was too small to properly display some of the ascendancy class names.
-
-
-

Widened dropdown to properly display ascendancy class names

---

src/Classes/PassiveTreeView.lua

The highlight circle around nodes was far too small the further you zoomed into the tree

Fix the highlight node circle being too small

---

src/Modules/CalcDefence.lua

Fixes #644 .
Reservation should be rounded up
- Tested on POB2
- Automatic tests successful
```
eNrtXVtX47iyfp78Ci_WmvPSafD90oees0JCgOHaBOjueWGZWCEGx0770hD22v_9VEm-yEnsOGH3bM4-9APtSFUlqVT6VCVL8u7_PE884ScJIzfwP29J2-KWQPxh4Lj-_eet66v-R3Prf_5o7V7Y8fh8tJe4HubIf7R-26U_BI_8JN7nLVPaEoaeHUVn9oR83joN_MctwY6GxHe6RfKR_zN4JOGWENvhPYlvsmLFW2Qf26E9jEl4giI7SRycBg4wxWFCtoSJ7fqDYPhI4oMwSKZQ1S3hp0ueGM3R6cX55dUWVOu33QvPnpFwENuxEMGfz1sdaJ59T3r2BP4Cl-0lwCLrurEtSqpoWoqoa1s7tcx7SRjFm0kYTAlxciZ1WzZ1qYr2IiT7oxEZxu5P0g3duDu2_WFRoiRWMS4hNretOurTxIvdqedid2QN2jYrW3G4KL9S_FUQ217vYlDUW1IVMC3TEk1TMox6viDO-Sqb-9WNx3se6HWDUo7ufTcmPKMmQsM1WdOB0dKUukIXmaFUU9q2VFVRVbCIOuaLwI0C_xWK2aDS3cTzYMTynJVavSQRCX_asVuuZLXRBZM711_ohCbqOLV9uxtERVcrtaQXJAQoiUsc4gqGARkGgD48i6TB8LOsJkUtF1BZ5ok7Is0p12pOyrBubTZrx_6gKd3agjer0CUgbjPKQZB4DSnjAvOk …
```

Incorrect rounding for reservation

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes # .
"Have you Pinned an enemy Recently" added to the config menu. The node Pin and Run uses this.
-
-
-

Add support for Pinned recently

---

src/Classes/ItemsTab.lua
src/Classes/TreeTab.lua
src/Modules/CalcSetup.lua

Fixes #704
Fixes #707 
There's an old skipProcessing flag in the code around timeLost jewel logic that we were using before the caching fix introduced in 0.4.0. The issue with this is every comparison was "missing" the timeLost jewel mods so the comparison always thought the jewel was being removed regardless of the item. This PR removes the flag entirely as it doesn't seem we really need it anymore anyways thanks to the caching solution.
707
<pre>eNrtPWtz27ayn6tfgfFM79wzVmy-H7lOz8hvp3bsWE6c9kuGFiGLDUUqfPjRM-e_312AD1AiKUo-TdWetDOODewugMViHwC42Pvn09QnDzSKvTB4syXvSFuEBqPQ9YL7N1sfbo5fWVv__Km3d-Ukk8vxfur5WKP81Pthj_1BfPpA_Tdbtr5FRr4Tx--cKX2zdUGjEQ2c6HmLODH85h6UdSd06gMNck7voc3A8SK6RRInuqfJx7wf0mcZ6E2cyBklNDrHNgZpEl6ELhBIohQwpo4XDMPRF5qcRGE6g75vkQePPnKYs4ury-ubLejnD3tXvvNMo2HiJCSGH2-2BjBe554eOlP4 …

Fix comparison tooltips for builds with Time-Lost Jewels

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
Vile Knight unique helm has a mod very similar to the Gladiator mods in PoE1. I stole the code, but had to add `totalLimit = true` to the 200% limit. Without that it would go to 800%. PoE1 was 1% more, here it's 4% inc. I guess the PoE1 version should technically also have totalLimit, but it's extremely unlikely to matter anyway, unless they buff the glad node to more than 1%.
-
-
-
https://maxroll.gg/poe2/pob/3j9jl011

Add support for Vile Knight Enemy in Presence Duration mod

---

src/Classes/ModStore.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Fixes part of #190
This adds parsing for "Your speed is unaffected by Slows" modifiers, such as on Pathfinder's "Relentless Pursuit" notable or the unique "Wanderlust" boots.
- Restarted PoB with rebuilt ModCache
- Lines in "Relentless Pursuit" and "Wanderlust" now parse correctly (blue)
- Added an Attack (Molten Blast) to my Character and noted default Attack Rate: **1.26**
- Attack Rate when "Are you chilled?" is active drops to **1.13**
- Allocating "Relentless Pursuit" bounces the attack rate back to **1.26**, ignoring the slow of the chill
https://pobb.in/uP9iiR1OtT2i

Add parsing for "Your speed is unaffected by Slows"

---

src/Modules/CalcDefence.lua

There seem to be multiple variables in CalcDefence that were made globals by mistake. This pr re-defines some of them to make them local variables again.

Fixup global variables

---

src/Modules/ModParser.lua

`(%d.+)` is incorrect for decimals. It should be `([%d%.]+)`.
Fixes #614.
- Tested manually on POB2
- Automatic tests successful
This can be reproduced with an empty build

Fix crash from importing item with Mana leech mods

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua

Fixes # .
- Adds support for Invulnerability's "Hits against Cursed Enemies ignore X Armour"
- Adds "Armour" / "IgnoreArmour" to physical damage effective DPS breakdown in Calcs
- _Notes:_ 
- _This purposely does not modify the "Armour" mods/values directly to avoid conflict with Armour Break mechanics_
- _This doesn't currently affect the "Impale" dmg calculation. As Impale is not currently part of PoE2, I did not touch that area_
- _This currently only affects offence calculation. If we ever want to calculate the effect of Vulnerability on the player, it will need updates_
- Mod gets parsed correctly
- Affects effective DPS correctly
- Does not cause negative Armour
- Has no effect if enemy Armour is 0
- Scales correctly with curse effect
- Gets displayed correctly in breakdown …

Add support for Vulnerability" ignore x Armour" mod

---

src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Updated the exposure values in the modparser to the poe2 value of 20%.
Also adjusted the ailment code to allow for the shock override to work, because for shock it kept taking the minimum shock value, so if you entered in a larger value for the shock it would just take the default 20% but if you went lower it would take the lower value.
- ran the tests and ensured they all passed
- made sure pob-poe2 still worked after the changes and rebuilt the cache files
- tested both the exposure and shock value in the app, with the changes to ensure they were accurate

Update Exposure Values in ModParser

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/ConfigOptions.lua

Fixes # .
War Banner aura was not implemented yet, it now applies the increased accuracy and more damage for attacks, and scales with valour stacks.
Valour stack is currently not limited in the config. It should be limited to 50 as base, but unsure if there is anything that alters the max stackable honour.
-
-
-
https://maxroll.gg/poe2/pob/na9lh05n
-Valour 50, no quality on gem
-Valour 50, 20 quality

Add support for War Banner aura mods

---

src/Data/SkillStatMap.lua

Fixes # .
Rolling Slam's second slam has mod "50% more damage against heavy stunned enemies". Now fixed.
- Verified that only the Second Slam gets the 50% more damage, not the Rolling Slam or First Slam.
- Heavy Stunned pops up in the config when Second Slam is selected in the Main Skill tab on the left.
-
https://maxroll.gg/poe2/pob/cd99605x

Add support for Rolling Slam "more damage against heavy stunned enemies"

---

src/Data/Skills/act_dex.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Fixes # .
Defiance Banner has more "more armour and evasion" as well as "increased movement speed" mods. Both scale by Valour stacks. Should work here.
Quality for defiance banner is not yet implemented. Mana Tempest uses the same stat. Seems weird to be on Defiance banner, does the banner count as empowering? I didn't think so, but dunno.
Also small text edit for Magnetic Salvo. They switched arrows and bolts at one point, likely because they repeat the order in a later sentence.
-
-
-
https://maxroll.gg/poe2/pob/1s9k707b
50 stack, 20 gem
0 Stack, 20 gem
Salvo Text

Add support for Defiance Banner

---

src/Classes/ItemsTab.lua
src/Modules/Data.lua

Fixes #743 
"JewelRadius..." mods for Time-Lost jewels do not have the "Small Passive Skills in Radius also grant" or "Notable Passive Skills in Radius also grant" lines. This PR updates the data.itemMods.Jewel once when starting the application and it shortens the affix labels in the dropdown so they fit, identical to what we're doing with Against the Darkness rangeLine labels.
<pre>eNrNW91z4zYOf17_FRrP3Fs2kWQ7tjNJO47tbNLJh2tnd3v30mEk2maXFl2JSuJ2-r8fQEryR0yFcu7hujO7loQfQAAECEDq-c-vC-480zhhIrqoe8du3aFRIEIWzS7qXx-vPnfqP_9UOx8ROX-YXqaM4xP_p9qnc3XhcPpMOQAbdSfgJEnuyYJe1MckmtG47pAkoFHYXz-4FxGtO5LEMyq_5VLd3z1Az0lMAknjW-TYS6W4EyEgZJwCYkFYNBHBDyq_xCJdgsC688zoi6a5uRs9jB_rsKpP5yNOVjSeSCKdBP66qPdAOzKjA7KAvwFFeAqQxnHL9U6b7dOG3_BOW_WTUvBlGifyMA6TJaVhAfKOfRPhKKbD6ZQGkj3Tfsxkf06iYC3OKGAPrX_cLCW_S7lkS87QR …

Update Time-Lost Jewel affixes with proper wording

---

src/Export/Skills/act_int.txt

Fixes # .
When exporting skills, the blasphemy statmap kept getting overwritten in act_int.lua. Just added the code to the .txt.
-
-
-

Fix Blasphemy in act_int.txt

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
Candlemaker unique gloves have "chance to ignite is doubled". Everything else that I see that is "doubled" uses a 100% MORE mod. So that's what I did here.
-
https://maxroll.gg/poe2/pob/sf3d800z

Add support for Candlemaker "chance to ignite is doubled"

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Copied the code for Discipline from a spectre. And applied a baseMod so that it doesn't affect the player, same as the Purity Auras on sceptres.
- Checked that ES is only gained by minions, and not the player.
https://maxroll.gg/poe2/pob/lteug0d5

Add support for Discipline

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

[Blasphemy ](https://poe2db.tw/us/Blasphemy) has a +1 metres to base radius effect on socketed curses, it's present within the game but it's missing from the current calculations.
Blasphemy's "active_skill_base_area_of_effect_radius" stat works as a base radius instead of an extra.
Added statMap for the skill so it works as extra radius.
```
skill("radiusExtra", nil)
```
Added socket group:
- Lvl 20 Blasphemy
- Lvl 20 Temporal chains (base radius 2.1m)
- Lvl 10 Flammability (base radius 1.8m)
- Magnified Effect (40% more Area of Effect)
The setup includes different base radius socketed spells and a support gem also to cover more scenarios.
Checked the Calcs tab -> Skill type-specific Stats table -> Radius value
Temporal chains (base radius 2.1m, missing the extra):
Flammability (base …

Fix Blasphemy's "Socketed Skills have +1 metres to base radius"

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

Fixes #731 .
- Original PR forgot to change "ArmourBroken" to "ArmourFullyBroken" in the statMap for "Exploit Weakness" support in `sup_str.txt` . Now it's fixed and works again.
- Check Config for "Is enemy Armour broken?" is set correctly (no manual value)
- Exploit Weakness support damage bonus applies correctly
_note: the 51.7% is a result of rounding due to the tiny damage values. modifier is correctly applied as "50% More"_

Fix "Exploit Weakness" Support not applying for "ArmourFullyBroken"

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/ConfigOptions.lua

Fixes # .
I copied the similar code from a spectre from PoE1 to start. We don't check if the enemy is cursed, I guess because just having a the curse skill gem itself auto sets the "enemy is cursed" flag.
I added a separate flag to the Boss config, as "Unique". Enfeeble acts a little different in PoE2, it applies the bigger damage reduction to Normal, Magic, and Rare. And the lesser the Unique enemies. In PoE1, it applied bigger to Normal and Magic, and smaller to Rare and Unique.
- Checked that the damage reduction changes according to enemy selection.
https://maxroll.gg/poe2/pob/vc95b008
Unique Boss
Set to "no"

Add support for Enfeeble "enemies deal less damage" mods

---

src/Modules/CalcOffence.lua

Fixes #726  .
Unleash support seal gain frequency is based on spell BASE cast time not modified by cast speed
import the build and select/deselect arcane tempo support on arc, gain time is not modified now while anticipation skill tree node will
[test build](eNrtfW1z27bS9uejX8HJzHmmndgJwVcpT3ru8bud2rFjOU6aL71pCbKYUKRCUn470_9-7wKkCJIgCVlpm7Y-Zya1AOwFcLFY7AIL4PX_3M0C7YbGiR-FPz0jL_RnGg1H0dgPr3969v5if7P_7H_-03t95qXT08n2wg8wx_hP71-v2Q8toDc0AEIdCEeBlyRvvRn96dkwikc0pknyTPOSEQ3HO0JeGsWzW-pBrc-01IuvaXqZN0D_lQDO1Iu9UUrjYwTfWqTRSTQGwjRe0GfazPPDYTT6QtODOFrMoe5n2o1Pb3mZo5Oz0_OLZ9DAf70-C7x7Gg9TL9US-OenZ1tQpXdND_0USLxgAeUNW9dN5wWxn71spdlexEm6683gzyWt6dq6bb0wjEbi4ZzScVHXi75lF_9vIjqL6d5kQkepf0N3Yj_dmXrhqKhVb6JbtezJIkj9eeBjN3SVP6xBY483FL6IUi_YPRsuyw76jmmTF0bftBzdtdrporS7OR_8dLodAG8fUQvSHl2HfkofSXwW-UkUrvF9I …

Fix unleash seal gain time depends on base cast speed

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
"Grenade skills have +1 cooldown use" from the Grenadier node works now.
- It only applies to grenade skills, so warcries correctly do not gain an additional use.
- I edited the tree to show +4 to test, and it does correctly add +4 uses in that case. So if they either buff this node or add similar to a unique later on, it will still work properly.
https://maxroll.gg/poe2/pob/tk7de00r

Add support for Grenadier tree node

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #749  .
shockwave now increase area of effect for every skill if you check the recent stun box and you wield a 2handed melee weapon

fix shockwave passive skill

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
Doryani's Prototype has different wording from PoE1. I feel it's fine to just update the old parsing to the new stuff, as I don't think PoE2 plans on using "nearby" anymore. Everything should be "in your presence"

Add support for "enemies in your presence have resistance equal to yours"

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Berserk gem was not implemented in, this solves that.
One small issue that I'm not sure on, which would also apply to PoB1. Rage effect doesn't seem to apply when the config is only 1 Rage. Not sure if it's intended, but I thought 0.2 leech would become 0.3 with 50% increased rage effect? When it's set to 2 Rage, it correctly shows 0.6 leech. Then 3 Rage is 0.8, then 4 Rage is 1.2. So I guess the effect is "additive" where it needs 100% total effect to add another stack of the mod, if that makes sense. Is this how it should function? Same applies for the life degen. Apologies if I didn't explain it well enough.
- Copied the code from PoB1 for the life regen mod. Which is related to [Rite of Ruin](https://www.poewiki.net/wiki/Rite_of_Ruin). The life regen scales from Rage Effect.
- As the …

Add support for Berserk Gem

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Sigil of Power works differently than in PoE1. In PoE2, it applies more spell damage per stage, up to 4x.
- Made sure the damage only applies to spells by adding a melee skill to the build.
- Went above 4 stages in the Config, properly ignores anything over 4.
https://maxroll.gg/poe2/pob/rit600w8

Add support for Sigil of Power

---

src/Data/ModCache.lua
src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Saffel's Frame disables the ability to block, and makes any modifiers to max block instead apply to max resistances. I believe this functions as it should, but please let me know if I there's a better way to do it.
- Equipping the shield disables block, and prevents any + max block mods from items like The Anvil from applying to max block.
- +5 max block Anvil applies +5 to all resists, including chaos.
- A modified -5 to max block Anvil lowers max res of all resists by 5.
- Melding of the Flesh isn't in PoE2, but regardless we don't need to add the max block calculation there as it affects all resistances equally.
Modifiers do not show up in the breakdown for Max Res. Not sure how to get them to show up. Would be nice to see, but not necessarily needed.
Also had to hardcode the 75 base …

Add support for Saffel's Frame "max block mods apply to max resist"

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes # .
For some reason we were missing the "to avoid chaos damage from hits" in ModParser.lua. Seems to work now, EHP changes when the slider gets moved around. I don't know where the actual calculations take place but I assume they work.
-
-
-

Add support for Perfidy "% chance to avoid chaos damage from hits"

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Currently it seems to work but i have to do some more testing.

Added support for break armour on hit

---

src/Classes/ModStore.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

1% more damage per 2 seconds the enemy is in your presence properly works. And it limited to the gems maximum damage.
Thanks to @Paliak, thresholdVar works properly for the culling strike mod. Culling strike is enabled once the enemy is in your presence for the required time.
Culling Strike code will need to be changed slightly if #618 gets added, quick fix at that point.

Add support for Attrition

---

spec/System/TestItemParse_spec.lua
src/Classes/Item.lua
src/Modules/ModParser.lua

Fixes #153 .
Rune: Soul Core of Cholotl
Rune: Soul Core of Zantipi
Rune: Soul Core of Atmohua
do not properly redistribute stats on gear.
Created mod in special mod list and updated logic in Classes/Item.lua to process flag and apply convert calcuations to base.
-Added custom item on Expert Barrier Quarterstaff base with all three runes and matched values to in-game calculation
-Added custom item on Expert Tribal Mask base with one rune + reduced Attribute Requirements and matched values to in-game calcs
-Matched Attribute Requirement calculations to items equipped
-Test case added to TestItemParse_spec.lua
https://maxroll.gg/poe2/pob/lt5vh0et
In-game Calcuations for items

Add support for Soul Core stat requirement conversion

---

src/Data/ModCache.lua
src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/Data.lua
src/Modules/ModParser.lua

Persistent skeletal minions have a base revival time of 8 seconds. A few uniques affect this, as well as 4 tree nodes, and one Buff gem (Sacrifice).
- Revival Time is listed under Skill-type specific stats. It only shows on the gem itself, it does not show when toggling "Show Minion Stats". I think that is fine, it's not a super important stat so keeping it on the gem keeps the minion breakdown uncluttered.
- Zombies do not have a revival time. They are duration based.
- SRS does not have revival time. Also duration based.
- Sacrifice uses a MORE multiplier to the revival time. Quality correctly reduces revive time by 5% at 20 quality, while gem itself increases the timer.
https://maxroll.gg/poe2/pob/6p9hk0z8

Add support for Minion Revival Time

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

The Shockwave on Stomping Ground had no base Phys damage. It does 80% to 120% of players strength as phys damage. The DPS calc itself is probably off as it says it triggers "when you take a step". Not touching that at the moment. Not sure how we would get a proper calculation.
- Base Phys changes according to Player strength. With 192 Strength 
- 192*0.8 = 153.6, rounded to 154 min
- 192*1.2 = 230.4 , rounded to 231 max.
https://maxroll.gg/poe2/pob/x69f50ze

Add Base Attack Damage for Stomping Ground support

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

The mod from Burden of Shadows internally uses a value of 100 for the stat `base_skill_cost_life_instead_of_mana_%` which also comes from Blood Magic, Lifetap and tree mods.
Talked to GGG and confirmed that all these mods should cap at a total summed value of 100 as you cannot over convert your skill cost
The game will probably fix this issue in the 0.2 patch later this week
Fixes #477

Fix Burden of Shadows Life cost calculation

---

src/Classes/PassiveTreeView.lua
src/Modules/Build.lua

Fixes #849 
PoE2 has different starting trees for each class. Currently just Witch changes the tree, but eventually the other classes (ones not released yet) will too. If the search bar was looking for "minion" as a Sorceress, and the class was switched to Witch, the nodes by the start would not get highlighted. Somewhat minor of an issue as you could backspace one letter to refresh the search, but worth fixing so that it is automated I think.
Minion nodes that otherwise would not be highlighted upon switching classes.

Rerun Node search when switching class

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Data/Skills/act_int.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/act_int.txt
src/Export/Skills/sup_int.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

A small number of skills have Ice Crystals, and two nodes on the tree affect crystal life. I tried to copy the Perfect Timing section, as I think showing the modifier values in the breakdown is cleaner than having a separate breakdown only for the effect modifiers, considering Ice Crystals aren't exactly the most important thing.
Also the description for Frozen Locus has a buggy Chilled Ground section. It's missing level scaling. So the displayed Ice Crystal Life shows 43 life at level 1, and 1 life at anything above. Related to that, Ice Nova Cast on Frostbolt has a similar problem. No level scaling, so the spell min and max damage shows 1-1 at anything above level 1.
https://maxroll.gg/poe2/pob/ku3l10ii

Add support for Ice Crystal life

---

src/Modules/CalcOffence.lua

Fixes #531  .
The cast time for warcries seem to be correct in the Tree tab (deriving from output.WarcryCastTime), but the dps is derived from generic speed that is related to cast speed
select cast speed or warcry speed in test build tree and now dps only scale with warcry speed
IMPORTANT: "99999% increased warcry cooldown recovery rate" is necessary otherwise the long cooldown will "hide" the dps change related to cast/warcry speed
[test build](eNqlW1932rgSf-5-Ch_OuW80YBsM7CF7TwJJk27-sJC2u089whagW9lmbZmEfvo7I9nGUGRs0ofWWPObkUYzo5mRO_zvm8-NDY1iFgaXDfOi3TBo4IYeC5aXjS8vtx_7jf_-8dtwQsTqeXGdMI4j1h-_fRjKHwanG8ovG1a3YbicxPET8ell4xuJIhZGDYPELg280d7IPAIWFAYFiZZUfM2Et7-bwGRFIuIKGj0g46tEhI-hBzgRJbRh-IQFs9D9QcWnKEzWMOGGsWH0VdHcP06epy8NmNyH4YSTLY1mgggjhr8uG1ewSLKkd0wAhPAE6M2Bc9FttErpr5MoFmPiw2M13GxNq …

Fix warcry speed scaled by cast speed instead of warcry speed

---

src/Modules/CalcPerform.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #853  .
- Change Unholy Might buff to use PoE2 effects instead: 30% of all damage gained as extra chaos damage (no more connection to Wither)
- Updated tooltips in the ConfigOptions
- Also added UnholyMightMagnitude into calculation already for the upcoming Lich node "Blackened Heart"
- Damage is added
- Phys damage no longer converted
- Unholy Might no longer enables "Wither" config options

Update Unholy Might effect and tooltip

---

src/Classes/ItemsTab.lua

When I changed the drop down in the rare templates to 2 buttons, I broke the CTRL+F search function for the Items tab.
This gets rid of the error. On 1080p where only one box shows as a time, it will properly select the search box. However on higher res (hard to test myself) it will always jump to the unique section. Not necessarily a problem, but it would be nice to have it jump to the search of the last selected Item List. That is if we have enough rare templates at some point that searching might be useful.

Fix Items tab search error

---

src/Data/SkillStatMap.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt
src/Modules/CalcSections.lua

Siege cascade does 50% MORE damage against immobilised enemies. Both impact and explosion get this damage boost.
I also added haveoutput to Ice Crystal Life in the Skill specific tab. It was showing for all skills again, I made an oopsie and was showing it for all for testing and didn't change it back.

Add support for Siege Cascade dmg vs immobilised enemy

---

src/Modules/ModParser.lua

- Add support for "Price Of Power" (Lich Ascendancy Notable)
- Non-channelling Spells consume Power Charges to deal 25% more Damage
- Might want to introduce some kind of "charge sustain" logic in the future, but that goes too far for now I think
- Mod parsed correctly
- Damage bonus is limited to non-channeling spells
- Requires minimum 1 "removable" Power Charge

Add support for "Price Of Power" (Lich Ascendancy Notable)

---

src/Modules/ModParser.lua

- Add support for "Rupture The Soul" (Lich Ascendancy Notable)
- Cursed Enemies Killed by you or Allies in your Presence have a 33% chance to Explode, dealing a quarter of their maximum Life as Chaos Damage

Add support for "Rupture The Soul" (Lich Ascendancy Notable)

---

src/Modules/CalcSetup.lua

Fixes #807  .
In PoB, mousing over a different weapon than the one that is equipped will show a stat comparison that seems to assume that the new weapon will replace the current weapon and unequip the shield.
https://pobb.in/ospAQfkM35dt

fix Weapon comparison with Giant's Blood

---

CONTRIBUTING.md
src/Classes/PassiveTreeView.lua
src/Classes/TreeTab.lua

The goal here was to make it easy to toggle set attribute nodes between the attributes with just a mouse click. If an attribute node is unset, then it will use the last used attribute to set it. If it's already set, it will toggle between attributes. This keeps state with the spec.attributeIndex so it behaves the same as using a hotkey to set the attribute.
- Fix contributions notes saying to use the x86 to x64 for debugging in JetBrains products
- enable a toggle-like effect when right-clicking an attribute node
- update modal dialogue's message to described the new right-click behavior

Toggle Attribute Nodes with Right Click

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Persistent Buffs get 50% LESS reservation. We could probably check for just SkillType.Buff as it just won't affect Buffs without a reservation anyway, but rather just check for both to be safe.
https://maxroll.gg/poe2/pob/5p5x40iu

Add support for "A Solid Plan" - (Tactition Notable)

---

src/Modules/Build.lua

Fixes bricked pob after loading a corrupt build causing all build loads after that to fail.
Add additional nil check for specList entry when activeSpec value does not exist in the table. This happens sometimes after corrupt builds, like in 0.2 before the Huntress class was added.
- Tested with poe2.ninja headless runner.
https://poe2.ninja/pob/15eb

Add nil check that causes load build to fail after corrupt build loaded

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

0.2.0 made the Purity and Discipline sceptres apply to player as well.

Fix Sceptres to apply to Self

---

src/Modules/BuildDisplayStats.lua
src/Modules/CalcDefence.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

- Add support for "Critical Strike" (Amazon Ascendancy Notable)
- Chance to hit with Attacks can exceed 100%
- Gain additional Critical Hit Chance equal to 25% of excess chance to hit with Attacks
- Mod gets parsed correctly
- Only applies to attacks
- Values for mainhand and offhand are calculated separately
- Works with different weapon types, including unarmed
- Uncapped hit chance is only displayed if above 100%
- Works with "Hits can't be evaded"
- It's currently possible to benefit from the mod twice if you also enter it manually in the config, but that's basically deliberate user interference. Might have to look at it again if we ever get the same mod on an item.
- **Impact of distance on accuracy is not yet accounted for** in PoB calculation (out of scope for this PR), so added …

Add support for "Critical Strike" (Amazon Ascendancy Notable)

---

src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

Fixes # .
Fully Broken Armour now causes enemies to take 20% increased Physical Damage from Hits
- attempted with normal mace, sunder skill
- checked that other elemental skill unaffected (frost bomb)
> eNrVW1tz2zoOfm5-hcbvjS-JcxunZxzbaTITN147aXefOoxE29xQog9FOfH59QuQutk1ZSp52s6kkUR8AAEQIAEpvb_eQ-6tqYyZiK4b7eNWw6ORLwIWLa4bz0-3Xy8af3076k2IWj7ObxLGcaTz7ehLT994nK4pB2DD8zmJ4x8kpNeNKYkWVDY8Evs0CgbFwA8R0YaniFxQ9TMT2vqN6CWRxFdUPiDDfqLEWASAUDIBREhYNBP-K1XfpUhWWt6a0TdDcz-ePE6fGjCpL70JJxsqZ4ooL4b_rht9UI4s6JCE8D-gCE8A0ukcdzon3U6jWYm6SWSsakJnK0qDnLp1fHp-0c1_LmyoiaSj-Zz6iq3pQDI1WJLIL4R2bbg9tK3jsyrqccIVW3GGDkoRJzb6uz-Yt616PwlF-HAyK0hhIifdVvv8ooM_1TihivkfoiwLsRIPEs5hqTrRTmlM5ZooWI5uvEX4wiIa9NcL9xUlKXmcGx9PScCSeEyVpHHJbZc27JhEZCDiwkSdbhXphEqIO7WFaB0AzKgvIFTLkHb7-PLs5Cz9OXeQuJ-PVfQDm1N3ylpapYC6s_mYHqOZK11tx …

Add Damage Buff for fully broken enemy armour

---

src/Modules/CalcOffence.lua
src/Modules/ConfigOptions.lua

Fixes # .
Pinned targets can no longer Evade.
- tested by running the client
N/A

pinned enemies have no evasion

---

src/Modules/CalcOffence.lua

- Global modifiers to Skill and Attack Speed now apply to Reload Speed
- Adjusted Reload Time breakdown accordingly
- Tree nodes that provide Attack or Skill Speed affect reload time
- More multipliers to attack time affect reload speed
- Breakdown displays
- Breakdown calculations match displayed end results
https://maxroll.gg/poe2/pob/t4acn00d
tree node effect:
breakdown:

Fix global attack speed mods not applying to Crossbow reaload speed

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Added a config option for Parried Recently. Tooltip for parry says that it does block the hit, so I set the BlockedRecently condition as well.

Add support for Parried Recently

---

src/Data/Skills/sup_dex.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/sup_dex.txt
src/Export/Skills/sup_int.txt

Another small PR.
Loyalty isn't fully done. Just the easy less life part was done. It still needs the `10% of Damage from Hits is taken from Supported Companion's Life before you`. We have previous work from Jinxed Juju in PoE1, just needs to be adapted. Would be nice to dynamically grab the Companions life rather than set it in the config.
Overextend needs the `You are Dazed for 5 seconds on Critically Striking with Supported Skill`. I imagine once we add Daze we could just make the player dazed if they Crit Recently?

Add support for Mysticism, Enormity, Strong Hearted, Loyalty, Overextend

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt

Both skills had the wrong flags on their damage buff stats

Fix damage flags on Considered Casting and Controlled Destruction

---

src/Classes/Item.lua

This mechanic was removed in 0.2 and is now meant to apply the quality to the skill that the sceptres grants. This functionality is not implemented in this PR
Fixes #907

Fix Quality of Sceptres affecting spirit total

---

src/Modules/CalcDefence.lua

I believe the only mult value that can ever appear there is Heightened Curse atm
Fixes #830

Fix Heightened Curse not affecting Blasphemy Spirit cost

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

The damage calculation was using your weapon when it should only be using the damage from the strength mod
Fixes #918

Fix Stomping Ground damage calculatiion

---

src/Classes/PassiveTreeView.lua

Fixes #904
this PR check for a valid socket object before call method

Fix crash when hovering over some jewel sockets with a 0.1 tree

---

src/Classes/ImportTab.lua

Fixes #906 
In Poe 0.2 have less jewel sockets, this PR enable importing builds from version 0.1 without error

Fix crash when importing 0.1 characters that used old jewel sockets

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

In patch 0.2 a bunch of nodes that used to say "% increased Effect of your Curses" now say "10% increased Curse Magnitudes". This wording did not have a parser. This PR adds a parser for "curse magnitudes" -> CurseEffect
- Loaded build using curse magnitude nodes and checked enfeeble damage reduction
https://maxroll.gg/poe2/pob/26fc20i8
Enfeeble giving 16% less damage w/ nodes allocated
Enfeeble giving 23% less damage w/ nodes allocated

Add support for "Curse Magnitudes"

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

0.2.0 changed some wording on a few keystones and other nodes.
- Blood Magic
- Necromantic Talisman
- Chaos Inoculation
- Eldritch Battery (new mod that doubles mana costs)
- Austerity Measures and other small nodes like it.

Fix some tree parsing in 0.2.0

---

src/Classes/TradeQueryGenerator.lua

Fixes issue mentioned on discord
Fixes #925
#8247 removed handling for this case. My intention was to make it so that when fulldps is the only weight and it is not set then it is effectively ignored but that caused this issue. This pr re-adds the if check that handles this situation as before.
- Test by attempting to find best Weapon 1 in test build
https://pobb.in/AGQ1ldvG_rUz

Fix "Could not generate search" error when using only full dps as a weight and not using full dps

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

The added life cost is mean to be a base cost and was instead being treated as a hybrid cost
Fixes #494

Fix Life cost calculation when using Sanguimancy and Archmage

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

30% MORE damage for heralds. Need a proper weapon equipped for the reservation to activate. Must switch the Stat Set to the actual damage part of the Herald.

Add support for Deadly Herald

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Fixes #917 .
- Fixes Giant's Blood Keystone after wording change
- Adds additional condition "UsingMartialWeapon" to `CalcPerform` for future use _(not related to Giant's Blood)_
- Mod gets parsed again
- Only applies to martial weapons (this was already the case before the wording change)

Fix Giant's Blood Keystone

---

src/Data/Skills/act_str.lua
src/Export/Skills/act_str.txt

Now that Ailment threshold is in, I added the stun and ailment threshold from Dread Banner.

Add support for Dread Banner ailment and stun threshold

---

src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua

- `isMartialWeapon` function I introduced in #931 turned out to be unnecessary so I removed it
- Having the base weapon stats added to output in `CalcOffence`  instead of in `CalcPerform` where a lot of the other weapon checks are done, didn't make much sense, so I moved it there. I also intend to move the Tactician mod from #931 to `CalcPerform` eventually
- Tactician mod from #931 still works as intended
- Amazon mod from #932 still works as intended
- (nothing else was using this section of the code for now)

Relocate code for addition of base weapon stats to CalcPerform

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

Skill cost is lowered when the Empowered config is set to true. Not specific to Mana cost, so it applies to Life cost with blood Magic too.
Accuracy is given 30% MORE when Empowered config selected.
With Blood Magic

Add support for Unerring Power

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Just sets the NoManaRegen flag if the Crit Recently toggle has not been set to true. If the box is not ticked, it shows 0 Mana Regen.

Add support for Nightscale "cannot regen mana" mod

---

src/Data/ModCache.lua
src/Modules/CalcDefence.lua
src/Modules/ModParser.lua

Gloamgown sets the base Energy Shield Recharge Delay to 10 seconds. This works as is, I am not sure on future proofing though. If they add any modifiers like +2 seconds to Base ES Recharge, it will need to be worked on again. Or if there is two forms of override, I am not sure how priority is determined for two overrides.
Anyway, not a problem for now. Just sharing thoughts.

Add support for Gloamgown base ES Recharge Delay

---

src/Classes/Item.lua
src/Classes/TradeQuery.lua
src/Classes/TradeQueryGenerator.lua
src/Data/QueryMods.lua
src/Modules/CalcSetup.lua

Closes #649
A small issue remains that since the enchants show up on unidentified items, megalomaniacs can be found unidentified which removes some information from the fetched item such as limit and name (and the unidentified tag for some reason). This PR does the minimal changes required for these unidentified items to be properly sorted and displayed.

Update trader to support PoE2 version of Megalomaniac

---

src/Data/Skills/sup_dex.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/sup_dex.txt
src/Export/Skills/sup_int.txt
src/Modules/ModParser.lua

Fixes #984 
Gambleshot still needs the 1/3 chance to fork, chain, and pierce mod.
Delayed Reaction trigger mod might not be worth implementing, but left it as red for now.
Burgeon caps at 4 seconds channelling, for 40% more damage. It doesn't "need" the Channelling Condition, but it felt better to have the Channelling box pop up along with the Seconds spent Channelling
EDIT: The stat itself has the spelling error.

Add support for Burgeon, Pinpoint Critical, Warm Blooded, and other partial gems

---

src/Data/ModCache.lua
src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt
src/Modules/ConfigOptions.lua

Added two configs, one for melee hit recently, and one for projectile attack hit recently. The gems look for 8 seconds, but I think we decided to implement anything from 8 seconds as recent for now. I abbreviated Projectile Attacks so that the line fit in the box. But maybe different wording would be fine? Kept it consistent for now.
Blindside gives MORE crit bonus and crit chance against blinded enemies.
Retreat and Pursuit use the new configs. They also prevent the skill from dealing melee or projectile damage. Equipping both gems on **Falling Thunder** makes it deal no damage at all, as it has a Melee and Projectile portion.

Add support for Retreat, Pursuit, and Blindside

---

src/Classes/ImportTab.lua

Fixes #968
Previous code had issues when the end user have selected previous tree instead of last one.
This PR fix that and also update the ui to select the last version

Fix a crash when importing a character with tree version 0_1 selected

---

src/Modules/CalcOffence.lua

- Adds Uncapped/Excess hit chance support for the distance based accuracy breakdown
- Fixes previous accuracy breakdown not account for ´noAccuracyPenaltyAtDistance´ mod for the non-config distance values
- Refactoring code for the ´breakdown.AccuracyHitChance´ in general
- normal hit chance values still displayed correctly
- excess values only displayed if `Condition:HitChanceCanExceed100` flag is present
- excess values only displayed if hit chance is above 100%
- hit chance for all distances is now the same with ´noAccuracyPenaltyAtDistance´
- still interacts correctly with "Hits can't be evaded"
- also still works for minions
https://maxroll.gg/poe2/pob/jom4u004
Previous display of uncapped hit chance:
Incorrect display with "you have no accuracy penalty at distance"
New breakdown

Improve Accuracy Breakdown for Excess Hit Chance

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Also affects the tree nodes by Huntress/Ranger. Including the +4 Melee Strike range mod, although there is no breakdown for that yet.

Add support for Daevata's Wind "past 8 seconds" mod

---

src/Data/Skills/minion.lua
src/Export/Scripts/skills.lua
src/Modules/CalcTools.lua

This is a temporary fix for the skill to work again. We should identify minion skills in a better way instead of counting the maximum number of levels

Fix Arc skill on Storm Mages not working

---

src/Data/ModCache.lua
src/Data/Uniques/wand.lua
src/Export/Uniques/wand.lua
src/Modules/ModParser.lua

When I first added the new unique, I didn't realize it could have multiple versions of the +4 mod. The mod wasn't getting parsed as it's a skill name, not a Skill Type, so I added a separate line for it. It seems to function properly, it gives +4 to the proper curse no matter if it's the active skill or not, and taking the tree node **Endless Blizzard** correctly still applies +4 to cold skills. So Hypothermia was +5 total.
However, if someone could implement this into the line just 2 below, and have it look for Skill Name as well as skill type, maybe that would be better? Didn't try myself, looked a little complicated and not sure if we'd want to complicate it more or have a separate line.

Fix Cursecarver variants

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

Fixes #1013 .
Dauntless had a GlobalEffect "Buff" for the multiplier. Because of that, it stacked per skill. The issue linked used a crossbow skill which has 2 parts, **Load Fragmentation Rounds** and **Fragmentation Rounds**. If you add another skill like **Arc** with dauntless supporting it, it will further increase the maximum buff for all skills. Removing GlobalEffect makes it just apply locally, and still shows up in the breakdown for more damage. It just doesn't show in the Aura and Buff skills, which it probably shouldn't anyway.

Fix Dauntless max damage stacking

---

src/Classes/Item.lua

Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/992
As there are now multiple runes of different types it becomes harder to guess the runes used on the item.
This PR aims to solve this issue by generating a minimal combination of runes that meets the stats present on the item. This means it will always generate a set of runes that add to the total if it can, otherwise it won't. This does however mean some runes combinations won't be accurately reflexed as they are ingame e.g. 
Will get imported as 
But I think this is a minor issue as it should be right in most cases of people using the runes. But will sometimes get it wrong mostly with runes values that linear combinations of others e.g. if some uses 2 lesser +20 life runes it will always be importer as a …

Add proper support for pasting items with lesser and greater runes

---

src/Modules/CalcActiveSkill.lua
src/Modules/CalcOffence.lua

The Gem attack speed multiplier was affecting the reload time of Crossbow skills as it as implemented as a more attack speed mod instead of modifying the base attack rate
Fixes #1006

Fix Gem attack speed multiplier affecting Crossbow reload speed

---

src/Modules/CalcDefence.lua

A breakdown-specific variable was calculated incorrectly (doubled) for chaos damage

Fix Eternal Life chaos damage resource drain breakdown

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Fixes #1055.
Adding support for the Quarterstaff tag that wasn't there alongside other similar ones ("while wielding a spear" mod is also missing, but doesn't exist on the tree/item so far)
Also, the "UsingStaff" tag seems to work only with Quarterstaves now and its a bit misleading, + there is no Staff tag itself (which makes node/modifier work as intended, but may be problematic later if those staff mods would appear)

Add support for "while wielding a Quarterstaff" (One with the River)

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Shyaba unique maul should always hit. Just setting the **CannotBeEvaded** flag like in PoB1. Accuracy still goes over 100% if the Amazon Notable **Critical Stike** is taken.

Add support for Shyaba "Always Hits"

---

src/Data/Skills/act_dex.lua
src/Export/Skills/act_dex.txt
src/Modules/CalcOffence.lua
src/Modules/CalcPerform.lua
src/Modules/CalcSections.lua

Fixes #1060.
Voltaic Mark shock effect mod was not yet implemented, and the Shock Chance mod was not applying. Had to make a few changes to calcs with help from @LocalIdentity.
Wish they would decide on magnitude or effect. Kinda awkward with mod names at the moment. I didn't touch SelfShockEffect for the player as they seem to use effect more often in that case.

Add support for Voltaic Mark shock effect

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Insulated Treads wasn't supported yet as we didn't have ailment threshold for the player until recently.
Nodes like Exposed Wounds had wording changed, again IMO to a worse wording. The nodes function properly, but there is no Armour Break/Hit breakdown yet.

Add support for Insulated Treads and "armour break on targets with ailments" node

---

src/Modules/CalcOffence.lua

- Mods that grant ailment chance for critical strikes only, were previously parsed, but not actually accounted for in chance calculations for poison and bleed. Now they are accounted for.
- Example: "10% chance to inflict Bleeding on Critical Hit with Attacks" from "Perfectly Placed Knife" passive tree cluster
- Also keeps the `"OVERRIDE"` check for ailment (bleed/poison) chance that is introduced in #1054 
- Only counted on Crit
- Correctly displayed in breakdown
https://maxroll.gg/poe2/pob/yj1he083
Bleed
Poison

Add support for bleed and poison chance on critical hit calculation

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

- Add support for "Zealous Inquisition" explode mod (Witchhunter Ascendancy Notable)
- "10% chance for enemies you kill to explode, dealing 100% of their maximum life as physical damage"
- "Chance is doubled against Undead and Demons" not supported yet, as we don't currently support enemy-type specific mods afaik
- Explosion damage isn't calculated correctly as that seems to be broken for all monster explosion skills in PoB2. E.g. it just takes the base damage of the weapon instead of % of monster life and it also appears to be using "Punch" in the background (need to look into that further)

Add support for "Zealous Inquisition" explode mod (Witchhunter Ascendancy Notable)

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Straight forward, just used the ChaosCanShock flag that was also used for Stormweaver notable.

Add support for Voltaxic Rift shock chance mod

---

src/Data/ModCache.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #1046 .
0.2.0 renamed a bunch of tree nodes (which IMO are now worse than before) so Banner tree nodes weren't increasing the effect.
Also fixed the config, which I initially broke in previous PR. Now it scales up to 75 properly if the player takes the + Maximum Valour nodes.

Fix banner valour config and tree nodes

---

src/Modules/CalcOffence.lua

The calculation was using a Sum instead of multiplying each more mod together
Fixes #1042

Fix calculation when using multiple "more Crit Damage Bonus" mods

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt

Fixes #1027 
in PoB conc effect didnt work on flicker strike because it was missing the "area" tag in the template file.
- checked in pob
- export skillgems works without errors
https://pobb.in/6KsPwgiyZpU6

Added area tag to flicker strike

---

src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcDefence.lua

Fixes #934
Modifiers to base blasphemy reservation such as the one from clarity were applying to the reservation caused by supported curses. Additionally this makes the reservation multiplier apply to all reservationFlat values without the need for special handling.
```
eNq9G2tv2zjyc_MrCAMLtNhL_EicNoHThWMnTYA8XDtp7z4VjETbvFCSK1FJvIv97zdDUg-7pkwlh-2HVhbnzZnhzFDt_fESCPLE4oRH4UmjvddqEBZ6kc_D2Unj_u5891Pjj887vRGV89vpacoFrnQ-77zrqR9EsCcmALFBPEGT5IYG7KQxpuGMxQ1CE4-F_qBYuIlC1iCSxjMmv2VMWz8Qe05j6kkWXyHBfiqj68gHDBmngBFQHk4i75HJL3GULhS_J86eNczl9eh2fNcAod71RoIuWTyRVJIE_jpp9EE5OmMXXAIKFSnAtxrNStjTNE7kkAbwuB1nsmDM3w42iLm8ToXkC8HRNAa-Y4MHeQdzGnqFBO2WlfhdJKkYjibbxdCQkYMtvnM5PxWgmxNdhL6chVwyZ_BRxJMorCW1E_AgFQJ81Al2zBIWP1HJHQUZRMEDDx1tck1DOogS6QY5YjEEi6yFMGFeBPFVl0dNzCs-Ze6QtfQwCHWleZ0eZxNXuNqEXyfQGBKMG-QkS …
```

Fix modifers to Blashpemy Spirit reservation applying to supported curses

---

src/Data/ModCache.lua
src/Data/Uniques/helmet.lua
src/Export/Uniques/helmet.lua
src/Modules/ModParser.lua

The way the mod is worded, it reads as if it should be granting generic damage to non-channelled spells, not spell damage to non-channelling skills. GGG appears to have made an exception for the mods on Rathpith where is grants spell damage and spell crit chance
Fixes #1030

Fix Rathpith Globe damage not working with Crown of Eyes

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt

This PR adds support for [Derang](https://poe2db.tw/us/Derange). 
I wasn't sure which ESCost mod I should be adding here, so I just went with the no mult one since theres no ES cost multi in game afaik.
The build provided has +1000 int jewel to demonstate scaling. I also added some fire mult to test non-ailment damage scaling (non expected).
- Give +1000 int to character
- Add Essence Drain + Derange -> See 80% more damage from Derange
- Give lots of fire damage mult to character
- Add Fireball + Derange -> See no damage scaling for fireball Ignite
- Verify that ES cost is equal to intelligence 
- 
https://maxroll.gg/poe2/pob/chkb200k
No parsing
Fireball ignite damage
+80% more damage (1015 int * 8%) on Essence Drain dot
+1015 ES cost (1015 int)
No Change to fireball ignite damage

Add support for Derange support gem

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

The mod was mistakenly added for only phys damage instead of all damage types
Fixes #1086

Fix Grasp of the Void damage gain not working correctly

---

src/Data/QueryMods.lua

Many of the jewel mods were not working correctly cause the similar radius jewel mod was causing a conflict and taking precedence
A proper fix is needed instead of manually removing all the radius jewel mods from ModJewel.lua and regenerating the Query Mods file

Fix many mods on jewels not being included in Weighted Search results

---

src/Data/ModCache.lua
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

Sturdy Ally adds player Strength to Companions, Tandem Assault adds Dex.
I used separate flags for these, as I believe Tandem Assault should stack with Dead Can Dance. That and I couldn't figure out a way to add a SkillType.Companion check in the modparser that would work.
Rhoa Mount has the Companion tag, so it gets the attributes from the nodes, while Skeletal Arsonist Minion does not.

Add support for Sturdy Ally and Tandem Assault

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Essentia Sanguis is a pair of gloves instead of a claw like in PoE1. Wording is different, but does the same thing as Ghost Reaver in PoE1 so just changed the one line in modparser.

Add support for Essentia Sanguis leech mod

---

src/Modules/Build.lua

Fixes #1076
The only logic handling hiding of the sub skill dropdown was for when there are no skill groups. Otherwise it was always set to true after being set for the first time.
This pr makes the sub skill drop down default to false inside of the `buildMode:RefreshSkillSelectControls` function.

Fix crash due to outdated state of sub skill dropdown

---

src/Classes/ConfigSetListControl.lua

Fixes #1077
Creating a new config set would save the entire table into self.selValue which is then later used as an index. Since the configSets table is indexed by ids instead it returns null and causes a crash.
This pr simply makes the save button function save the id instead of the full table. This also makes the newly created config set highlight nicely.
See reproduction steps in issue

Fix crash when deleting newly created config set

---

src/Modules/CalcDefence.lua

Fixes #224
The PerStat mod from the Beidat's Hand Infernalist ascendancy notable did not work due to Life amount not being present in the output at the time of calculation of globalBase EnergyShield. This pr attempts to fix this by running the doActorLifeManaSpirit before calculating the primary defences and then again after to account for potential conversion mods. This should work correctly as any values written by doActorLifeManaSpirit should be overwritten by the second call. I'm currently unsure whether there are cases that could cause issues with this proposed solution.
-Test the mod by itself
-Test with GhostWrithe (PerStat applies after conversion, is that correct?)
```
eNqlW1tz4rgSfh5-hYuqrTqnNgMGcwkpslsJ5FaVCwvJzNmnKcUI0BnZ4thyEmZr_vvplmxzGWTkZB8yxu6vb-puqdve_p9vAXdeaBQzEZ5WGzW36 …
```

Fix Beidat's Hand Energy Shield per Max Life mod not working

---

src/Data/Skills/other.lua
src/Export/Skills/other.txt

Fixes #1112
Concoctions skills seem to be missing area base flags which is causing them to not have the ModFlag.Area bit flag set in CalcActiveSkill. This makes the area more damage mod from Concentrated Effect not apply.
```
eNrVXNty4zYSfR5_BUpV2dqtyVgiqYvtlZOSb2NX2WNHsmc2TymYhCyuIVIhQdtKav59uwHeJBMkaO9DkocMRZzuBg4aQKMBevzzy5KTJxbFfhgcdqzdXoewwA09P3g47Nzdnn3a6_z80874horF9fwo8TmW2D_tfBjLH4SzJ8ZBsENcTuP4C12yw86UBg8s6hAauyzwjosCVDP3Aw8LBY0emPiame79hjoWNKKuYNElqp0kIrwKPZATUcI6ZEn9YBa6j0x8jsJkJa0--exZYS6ubq6ntx2o2ofxDadrFs0EFSSG_x12JtBE-sBO6BL-D1KUJyCy1xvsDgZDa98Z7A-cUadbK3yURLF4m4bZijEvF7J2-zrgTcRO53PmCv-JHUe-OF7QwC3MDXRybbFXCRf-ivvYESne1uHPX6m2ej0d-DYUlJ_czAqsZY92R6O94cjqOc6gXi4UuZzWwhEHLssWgPvdkWOPRkN71BtaOrlvvli8krV7Q2d3YFn9_sjp9WtlLx4CX7A3NA2Fb0I_DoN38PKGBh8nnMNgLUtqSZ2ymEVPVPibldTij8PlvR …
```

Fix missing area base flag on concoction skills

---

src/Data/Uniques/Special/Generated.lua

The patch notes for 0.2.0 were wrong and it was meant to say that the jewel now uses a small radius instead of large
Fixes #1109

Fix Against the Darkness using Medium radius instead of small

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/act_str.lua
src/Export/Skills/act_dex.txt
src/Export/Skills/act_str.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ConfigOptions.lua
src/Modules/ModParser.lua

Fixes #1117 .
- Add support for generic "hazard"-related mod parsing (damage & duration)
- Add support for Hazard x% chance to rearm (tree nodes were not supported, and the `SkillStatMap` used `"DPS"` and `"INC"` , which didn't apply to the explosion, which is the actual hazard, and was also harder to analyze in the breakdown). It's now using a `"MORE"` damage mod with an additive multiplier of "`ChanceToRearm"`
- Add support for "x% damage per Hazard triggered recently" ("Escalating Mayhem")
- Add support for "Enemies affected by your Hazards recently have ..." ("Shredding Contraptions")
- Mods get parsed correctly
- Only applies to Hazard skills (Spearfield and Caltrops)
- "More" damage from Rearm Chance is additive with itself
- "Escalating Mayhem" adheres to globalLimit
- "Chance to …

Add support for "Hazard" related mods

---

src/Data/Skills/sup_str.lua
src/Export/Skills/sup_str.txt

Confirmed by GGG that it should be scaling with melee damage and that its a bug in the game files that we can see that it isn't currently included.
A future patch to the game will probably add a skilltype flag for the skill so I'm not going to add anything myself for now
Fixes #1141

Fix Stomping Ground not scaling with Melee Damage

---

src/Classes/ImportTab.lua

Fixes #1130
This fixes a stack trace that would appear if someone imported a character with a skill from an item that didn't have any support gems

Fix support gems imported on skills from items causing an error

---

spec/System/TestStatDescriber_spec.lua
src/Modules/StatDescriber.lua

Fixes #1168
When running Path of Building on Linux/WSL, the application failed to load skill-specific stat descriptions due to case-sensitivity issues. Generated stat description files sometimes reference parent scopes with lowercase "specific_skill_stat_descriptions/<name>" prefixes, but the actual directory is "Specific_Skill_Stat_Descriptions" (title case). This caused runtime errors like "cannot open Data/StatDescriptions/specific_skill_stat_descriptions/herald_of_thunder_statset_1.lua".
Additionally, the StatDescriber was using incorrect file closing syntax that could leak file handles.
- Start PoB in Dev Mode on Linux/WSL
- Open a build including Herald of Thunder or other affected skills
- Previously: error "cannot open Data/StatDescriptions/specific_skill_stat_descriptions/<scope>. …

Fix: StatDescriber scope loading on Linux/WSL with comprehensive test coverage

---

src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt

Fixes #1161
Just supports the 20% more damage mod on Deliberation, the movement speed mod hasn't been touched.
https://maxroll.gg/poe2/pob/r36yx0wd

Add support for Deliberation Damage Mod

---

CONTRIBUTING.md

* mostly a copy-paste from pob1
* consolidated debugger snippet insertion instructions
* fix(?) snippet indentation (spc->tab)
* fix old broken link to busted site

Update EmmyLua VSCode debugging tutorial 2

---

src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt
src/Modules/CalcPerform.lua
src/Modules/CalcSetup.lua

Add support for Muster Support 
- Checked Muster Support in game vs pob
https://pobb.in/pB3VQ0pS3vf9

add support for Muster Support

---

spec/System/TestAttacks_spec.lua
src/Data/FlavourText.lua
src/Data/Uniques/belt.lua
src/Export/Uniques/belt.lua
src/Modules/CalcOffence.lua

* efficency / efficeny -> efficiency
* Brynabas -> Byrnabas
* whitespace

fix: spelling efficiency/byrnabas

---

src/Classes/ImportTab.lua

Fixes #1185.
Fixes #1181 (didn't test but brain says it should work)
Decreased logout button size a little, stopped the importer from running on loading any build, and show the logout button in more cases.

Fix automatically running character import on loading build, and show logout button in more cases

---

src/Classes/ItemsTab.lua
src/Classes/Tooltip.lua

Removed a 2 pixel offset for tooltips with pretty UI on. Originally it matched the total height of the OG tooltip, but it created uneven black space. Removing it evened out the black space, and shrinks total tooltip size a little.
Also stretched some headers to better fit letters like q and p that go below the base font line.
And shrunk the separator below corrupted as it was slightly bigger than the rest.

Fix vertical spacing and tooltip header size

---

spec/System/TestAttacks_spec.lua
src/Modules/Data.lua

Default Unarmed Critical Strike Chance was changed from 0% to 5% as of patch 0.3.0

Change default Unarmed Crit to 5%

---

src/Classes/SkillsTab.lua

The hover tooltip did not show the gem name per instance, so Companion/Spectres were showing the same on all tooltips.

Fix hover tooltip showing same name for all companions/spectres

---

src/Classes/PassiveTreeView.lua

Copy of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8635

Add shortcut to copy node text from Passive Tree to the clipboard

---

src/Classes/TradeQueryGenerator.lua

Copy of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8586

Keep Max Price and Max Level between Trade Queries

---

src/UpdateCheck.lua

Copy of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8469
Includes https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8721

Resume failed update feature

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

**Adds support for mod:** "Enemies in your presence are slowed by 20%"
Tested that it only applies when enemy is in presence (distance <= presence radius)

Add support for "Apex of the Moment" (Chronomancer)

---

src/Modules/CalcTools.lua

Attribute requirements for gems have been changed in 0.3 and using a value of 1.7 instead of 2.25 accurately reflects the values shown off in the 0.3 reveal stream

0.3 - Update gem Attributes requirement formula

---

src/Classes/PoEAPI.lua

Fixes # .
This may or may not be specific to my environment, i.e. Linux starting PoB through wine.
My goal was to import my character using the import API. The issue happens when I go through the authentication flow, as the URL opened in my browser was truncated at the first space, resulting in a invalid webpage opening, and the inability to authenticate.
In the character import screen:
- Logout if previously authenticated (*Logout from Path of Exile API*)
- Attempt to authenticate again (*Authorize with Path of Exile*)
- Verify that the browser manages to open the authentication page
N/A
App logs:
```
Server started on 0.0.0.0:49082
Redirect URI: http://localhost:49082
Opening URL: https://www.pathofexile.com/oauth/authorize?client_id=pob&response_type=code&scope=account:profile …
```

Fix invalid authentification URL being opened 

---

src/Modules/CalcDefence.lua

PoE2 (at least as of 0.3.0) allows more than 100% of Armour to apply to other damage types. `CalcDefence` previously capped this value at 100%.
This item would make no sense if >100% didn't have an effect.

Remove cap on "x% Armour applies to y Damage"

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

New passive tree nodes were introduced and wording on some of the existing mods was changed. to now include a "+" or "also", or no longer include "taken from hits"
**Note:**
I chose to have two separate lines for the versions with and without "taken from hits" because afaik there is no safe to include patterns for an optional string that contains multiple spaces with the way the patterns are currently processed. Something like `t?a?k?e?n? ?f?r?o?m? ?h?i?t?s?` has too high of a chance for false positives imo.

Add support for new "+X% of Armour also applies to Y Damage" mods

---

src/Data/SkillStatMap.lua
src/Data/Skills/sup_dex.lua
src/Export/Skills/sup_dex.txt
src/Modules/ConfigOptions.lua

- Stoicism support:
- Implemented ramping more Damage (cap 20%), resets on roll/travel
- Added config: Seconds building Stoicism
- Innervate fixes:
- Fixed duration stat key so gem shows as supported on tooltip
- Removed Innervation checkbox; use “Killed a Shocked enemy in last 3s”

Implement Stoicism support and fix Innervate Support

---

src/Data/Uniques/helmet.lua
src/Export/Uniques/helmet.lua

Fixes #1267
We were missing the Mask of the Sanguimancer Unique from 0.1.0.

Add Mask of the Sanguimancer Unique

---

src/Data/Skills/act_dex.lua
src/Export/Scripts/skills.lua

Explosive Spear had `active_skill_base_area_of_effect_radius` as a remove stat but it did not exist in the base stat set for the skill so it was incidentally removing the stat from the following stat sets
Fixes #1258

Fix incorrect radius on Explosive Spear

---

src/Data/Uniques/gloves.lua
src/Data/Uniques/helmet.lua
src/Export/Uniques/gloves.lua
src/Export/Uniques/helmet.lua

Fixes #1290  .
These two uniques were still on basetypes that were removed, so they weren't showing up in the uniques list

Fix incorrect base types on Crown of Eyes and The Prisoner's Manacles

---

src/Modules/CalcDefence.lua
src/Modules/ConfigOptions.lua

Updates the tooltip and fixes the handling for the Stormweaver node even though it doesn't work anymore

Update Arcane Surge config tooltip

---

src/Classes/Item.lua

In the function to try and guess how many of the same rune there are on an item, it expects to see an integer somewhere in the modline
The fix sets the value as 1 but should be fine as if a mod has a number in it, the value will be overwritten anyway
Fixes #1279

Fix Crash when using Bow with +1 Arrow Rune

---

src/Data/Uniques/Special/Generated.lua

Fixes #1273.
The modifier ID does not match the stats provided for the `Gained As` mods. Kinda gross.

Fix Heart of the Well modifier names

---

src/Classes/GemSelectControl.lua
src/Classes/SkillsTab.lua
src/Data/Skills/act_dex.lua
src/Data/Skills/act_int.lua
src/Data/Skills/act_str.lua
src/Data/Skills/other.lua
src/Export/Scripts/skills.lua

We were still using the old logic for secondaryGrantedEffect that PoB 1 uses, so if any skill had a quality stat on a additionalGrantedEffects, it wouldn't show up in the quality tooltip or get added to the main gem tooltip
We now iterate over the first 2 entries in the additionalGrantedEffects list to check for quality stats in them
Note: We technically handle quality stats wrong for quite a few gem. Some gems have restrictions on the stat sets the quality stat should apply to but we currently just apply the quality stat to all the stat sets.
I'll look into fixing this in the future
We were also missing the export of the quality stat on Hand of Chayula
Before:
After:

Fix quality stats on gems not showing up in gem tooltip

---

src/Classes/GemSelectControl.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ancestral_cry_projectile.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ancestral_cry_statset_0.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ball_lightning_statset_2.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/bone_cone.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/burst_shot_incendiary.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/create_mirage.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/dark_effigy_projectile.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/feast_of_flesh.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/foresight.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/frost_bomb.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/hand_of_chayula.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/igneous_shield.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/poisonbloom_arrow_statset_0.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/rapid_shot_permafrost.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/ravenous_swarm.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/reap.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/sorcery_ward.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/thunderfist_statset_1.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/toxic_domain_statset_0.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/toxic_domain_statset_1.lua
src/Data/StatDescriptions/Specific_Skill_Stat_Descriptions/wrath_aura.lua
src/Data/StatDescriptions/active_skill_gem_stat_descriptions.lua
src/Data/StatDescriptions/meta_gem_stat_descriptions.lua
src/Data/StatDescriptions/skill_stat_descriptions.lua
src/Export/Scripts/statdesc.lua
src/Export/statdesc.lua
src/Modules/StatDescriber.lua

GGG added a new variant in the stat description files that is meant to be used only for gem quality tooltips.
We were not handling it properly before so if the same stat existed on the gem, the display for the stat was broken too.
e.g. Arc showed "Chains an additional time" instead of "Chains 9 times"
Now properly handled in the stat export and in stat describer
Before:
After:

Fix display of some stats in gem tooltips

---

src/Modules/CalcActiveSkill.lua

Totems use the same level scaling as minons where their level is 2x the gem level

Fix Totems using the wrong level for Life calculations

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Modules/ModParser.lua

Didn't parse quite a few nodes on the ballista specific clusters
Correctly works with Mortar cannon which counts as a Ballista too

Add support for Ballista Nodes on the Tree

---

src/Classes/DropDownControl.lua

No sure what is causing the list to find a nil label but this should fix it
Fixes #1278

Fix Crash on Tree tab

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Data/Skills/sup_int.lua
src/Export/Skills/sup_int.txt
src/Modules/CalcPerform.lua
src/Modules/ModParser.lua

EDIT NVM This shouldn't apply twice I think
Hulking Minions changed the stats, so slight change there.

Add support for Gigantic Following and fix Hulking Minions

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Fixes # .
Parsing of daze chance, and blind-equivalent implementation
- Confirm parsing alongside other "ailments".
- Compare to 'blind' and implement in similar fashion.
- Confirm acceptable parserCache updates.

Add breakdown for Daze Chance on Calcs tab

---

src/Classes/Item.lua

Fixes #1254
Copying items from in-game separates out each damage type instead of grouping them as "Elemental Damage" like in PoE1.  This PR also ignores the "Requires" line, as it comes from the base item.
The bow in the linked issue has already been mangled by our reformat, so it would have to be re-imported from the game to see the fix there.
Tested with this item:
```
Item Class: Two Hand Maces
Rarity: Rare
Skull Crack
Crumbling Maul
--------
Physical Damage: 90-114 (augmented)
Fire Damage: 6-10 (fire)
Critical Hit Chance: 6.01% (augmented)
Attacks per Second: 1.16 (augmented)
--------
Requires: Level 38, 68 (unmet) Str
--------
Item Level: 38
--------
Gain 1 Rage on Hit (enchant)
--------
Causes Enemies to Explode on Critical kill, for 10% of their Life as Physical Damage (implicit) …
```

Fix base modifiers showing up as explicit mods

---

src/Data/QuestRewards.lua

fix: The Seven Pillars downsides

---

.github/workflows/test.yml
src/Modules/Main.lua

Add a github CI job to automatically check if the ModCache needs to be regenerated
You can see an example of the test failing on https://github.com/Musholic/PathOfBuilding-PoE2/pull/2

Automatically check if the ModCache needs to be regenerated

---

src/Data/Skills/minion.lua
src/Export/Skills/minion.txt
src/Modules/CalcActiveSkill.lua

We were using a old variable name so the check to find which minion stat set was used always failed and used 1
Also added the attack tag to the gas arrow explosion so the damage numbers would show up
Fixes #660
Before:
After:

Fix minion Gas Arrow skill not showing Poison / Explode damage

---

.github/tweak_changelogs.sh
.github/workflows/beta.yml
.github/workflows/release.yml

This PR modify the beta workflow to use release-drafter as a way to get generated changelogs.
It refactors the tweak_changelogs logic (with comments thanks to the AI otherwise it's hard to understand) and handle CRLF issues of the generated changelog since we need to have proper hash generation in the manifest file for the auto-update mechanism.
The workflow is hard to test beforehand (without actually doing a beta release or a release) but I tested a similar version on my Last Epoch fork (of pob1). I should be able to test this particular commit on my fork of pob2 later on.
Let me know if you have questions or remarks

Generate the changelog for the beta releases

---

src/Classes/ImportTab.lua
src/Classes/PoEAPI.lua
src/Launch.lua
src/LaunchServer.lua

This is essentially a re-submit of #1345 that fixes a crash in it.

Fix subscript errors

---

src/Classes/PassiveTreeView.lua
src/Modules/CalcSetup.lua
src/Modules/ModParser.lua

The mods granted by the timeless jewel do not appear in the node tooltip cause it is pulled from the tree file instead of the modified one. Not sure if this will cause bugs elsewhere
The change in CalcSetup is needed so that it doesn't run the whole calc setup file every time you allocate a node but it causes the issue where stat don't get added to the base attribute nodes. Not sure how to fix this
Test build:
https://maxroll.gg/poe2/pob/sora0cqv
Before:
After:

Fix Abyss Timeless jewel mod display

---

src/Data/SkillStatMap.lua

For some reason the only way I can tell if a skill combines dual wielding hits is if it has this more damage mod on it
Fixes #643

Fix many Melee skills not hitting with both weapons when dual wielding

---

src/Modules/CalcOffence.lua

When hitting with both weapons at once, only 1 of them needs to crit for the resulting hit to count as a crit
Not sure if this applies to other stats

Fix Crit Chance when hitting with 2 weapons at once

---

src/Classes/TreeTab.lua

Fixes #1381.
Adds line to the passive tree search box tips: 
`To search for multiple terms: (increased.fire.damage|increased.area.of.effect|etc)`

Add passive tree search tip

---

src/Classes/GemSelectControl.lua
src/Data/Gems.lua
src/Export/Scripts/skills.lua
src/Export/spec.lua
src/Modules/CalcSetup.lua
src/Modules/Data.lua

The Crossbow skills have their Ammo skill as the GrantedEffect entry so we were previously loading them first in the stat set list.
This also caused the Ammo Skill to be used in all the places the skill name showed up like the sidebar, skill list, calcs tab etc
Build:
https://maxroll.gg/poe2/pob/9phj0dep
Before:
After:

Load Crossbow Damage skills by default instead of Ammo Skill

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Modules/BuildDisplayStats.lua
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

Many skills allow you to move while casting / attacking and its helpful to know what your movement speed is while doing do
Does not take into account the movement speed / penalty when using the Rhoa mount with skills though
Build
https://maxroll.gg/poe2/pob/552zf0jj

Add Movement Speed while using skill to sidebar

---

src/Data/ModCache.lua
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

After much trial end error it seems that handling the cost like this correctly rounds for about 20 different situations. Its possible that it is still wrong but I cannot tell
Also fixes the handling for added Mana cost from Mind of the Council

Add support for Rathpith Globe Life Cost mod

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Data/Skills/act_int.lua
src/Data/Skills/sup_dex.lua
src/Export/Skills/act_int.txt
src/Export/Skills/sup_dex.txt
src/Modules/CalcOffence.lua
src/Modules/ModParser.lua

Skill speed also affects totem placement speed
Also fixed a number of supports and buff skills that weren't affecting Warcry Speed
Fixes #1406

Fix Skill Speed not affecting Totem Placement Speed

---

src/Classes/CalcBreakdownControl.lua
src/Modules/CalcDefence.lua

The reservation values for minions was off slightly for some minions and it seems that the game uses rounding instead of ceil for the flat costs
Also added the minion count to the breakdown as it made sense to be there and was annoying to not have it show up there
https://maxroll.gg/poe2/pob/u93400c2
Before:
After:

Fix Minion Reservation values + add Minion Count to breakdown

---

src/Classes/Tooltip.lua

All Jewel sockets on the tree would show the desecrated icon if a jewel with desecrated mods was socketed in it. This is the simplest fix, and I'm not sure where else I would change this anyway, as it's something to do with how jewels are assigned to the socket nodes. The icons still show properly when hovering the socketed jewel.

Fix Header Influence Icon Showing on Jewel Sockets

---

src/Data/SkillStatMap.lua

The stat saw mapped to Vaal Blade Flurry in PoE 1 but wasn't updated for PoE 2
Fixes #1450

Fix display name for Blind II effect mod

---

src/Data/ModCache.lua
src/Data/SkillStatMap.lua
src/Data/Skills/act_int.lua
src/Export/Skills/act_int.txt
src/Modules/CalcOffence.lua
src/Modules/CalcSections.lua
src/Modules/ModParser.lua

We were previously handling the revive time mods as time mods instead of speed mods so stacking 100% revive faster would make the revival time 0 instead of half as long
Also fixes an issue where we were not showing the revival times for
Spectres, Companions, Rhoa Mount, Infernal Hound and Manifest Weapon
Fixes #1468 
Build: https://pobb.in/j2ln1AORvOB3
Before:
After:

Fix Revive Time calculation and show time for Spectres / Companion

---

src/Data/Spectres.lua
src/Data/WorldAreas.lua
src/Export/Minions/SpectreList.txt
src/Export/Minions/Spectres.txt
src/Export/Scripts/worldAreas.lua

Removed Bloodthief Queen as it was disabled in patch notes. Most changes are just audio tags.

Update Spectres and World Areas to 0.3.1

---

src/Export/Main.lua

Since we added a few more scripts, it's worth increasing the size of some of the boxes. I also added a Copy button to the result box, to easily copy errors. Example with forced error:
```
Classes/Dat64File.lua:103: Unknown key MonsterVarietiesKey2 for monsterpackentries.datc64
stack traceback:
[C]: in function 'error'
Classes/Dat64File.lua:103: in function '__index'
Scripts/worldAreas.lua:20: in main chunk
[C]: in function 'PLoadModule'
Classes/ScriptListControl.lua:21: in function 'OnSelClick'
../Classes/ListControl.lua:369: in function 'OnKeyDown'
../Classes/ControlHost.lua:39: in function 'ProcessControlsInput'
Main.lua:427: in function <Main.lua:418>
[C]: in function 'PCall'
Launch.lua:56: in function <Launch.lua:53>
stat_descriptions.csd loaded. (9918 stats)
Soul Cores exported. …
```

Add copy button to exporter and increase script list size

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Simple mod parsing. Confirmed movement speed doesn't change when toggling the hidden config option,

Add support for Shankgonne "you cannot sprint"

---

src/Data/ModCache.lua
src/Modules/ModParser.lua

Wording changed at some point me thinks.

Add support for "duration of bleeding on you"
