src/Classes/PassiveTreeView.lua
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/207
=> Fix Passive Nodes hover display when Hulking form is allocate

src/Data/ModCache.lua, src/Modules/ModParser.lua
=> Add support for Monk's Reality Rending node

src/Data/Skills/sup_dex.lua, src/Export/Skills/sup_dex.txt
=> Fix Scattershot Attack/Cast speed value

src/Data/ModCache.lua, src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Fixes #291 
Parse "2% to Max Fire Resistance for each 40% Uncapped Fire Resistance"
<pre>eNrtPWtz2ziSn0e_gqWquborKzbfj5wzW7Zsx55YsSM5cWa-pGARkhhTpMKHH9na_37dAJ8SQcnyZMs7l51aRSK6G0B3ox9Ag97_x8Pcl-5oFHth8Kar7MpdiQbj0PWC6Zvux6uTV3b3H7919i9JMruYHKaejy3qb51f9tkPyad31H_TdayuNPZJHL8nc_qme02iyAujrkTiMQ3cfq3lJgISFBoTEk1p8invXP6iAJEZicg4odE5Ej5Ik3AQuoA3IX5Mu9KceMEoHN_S5G0UpgsYcVe68-g9BzobXF4Mr7owul_2L33ySKNRQhIpho833QOYJZnSIzKHT8AifgoolqIZu6pqqLqu27bT3WtFPkyjONmOwmhBqVsgKbu6CPAyoseTCR0n3h3tR17Sn5FgXHZniPAaYHVxLwg9SP3EW_geyiLDUHcVTYRyukLftkWwV2FC_KPLUQHqOLazqymGpquqrRvteGFS4MkiyEMf-FntQdFseddUbUs3Ta0dqy5A05G1XUXXLA3GJ0I8mwZeQqv9QW-yYti2aalrkOrdaSogmpqhm-vYFya1-ekmzE_XTU3TxEqQ-j6sriqekINDGtPojiSw-DaC74fzGy-g7sHdtDIozbB3dQ3V31DEyyei5GLC1XpIXC-NBzSJaFxZD8IpDUhA-mFcqoRqt8Je0ghsTlJDkdcgjOg4BDNVRdEcZ4NemnG …
=> Add support for Unnatural Resilience notable

src/Data/Skills/sup_dex.lua, src/Export/Skills/sup_dex.txt
Fixes https://github.com/PathOfBuildingCommunity/PathOfBuilding-PoE2/issues/406
Chain support was applying less damage modifier to dot damage.
https://pobb.in/zAIRdICH_Pt4
=> Fix Chain Support applying to all damage instead of just hits

src/Modules/CalcPerform.lua
Fixes #232 .
Onslaught is 10% ms in PoE2 instead of 20% ms (PoE1).
NOTE: Skill speed implementation seems to be not done yet, will need updates in later PRs
- Compare to in-game numbers
```
eNrtPNty27iSz9FXoLQ1-2LZ5l1S1p5T8l0T2_FIdnxmX6ZgEZIYU6SGBH3JqfPv2w3wJpmgKHu2tmZq85BIQHej0Td0NxAd_ONl4ZMnFsVeGBy29T2tTVgwCV0vmB22727Pdnvtf_zcOrihfP51epR4Ps4YP7c-HYgvxGdPzD9sW4A38WkcX9MFO2yPw2jCIhbHbULjCQvc42LueB6FQbigAUC0CafRjPFvGQPa7zoQmtOITjiLLpH4IOHhVegC5pT6MWuTBfWCcTh5ZPw8CpPlYdtskyePPUug4dXN19FtGzj8dHDj01cWjTnlJIa_DtsD2CmdsRO6gL8Bi_oJoOha19kze13Hcvp902zv1yIfJVHM30dhvGTMLZD2eoYK8iZip9Mpm3DviR1HHj-eo7xK66kQtwa-SnzuLX0PlZEiKLm6qKCtJH4bcuqf3IwL2L7d39MM29a7ttHt1-OFPMdTrnDv8fmRDyJ9xyrDWeBxVkbsWXt233TqFnuLZGiWuefofb1-NUS-Cb04DD4gkC2YPU58H_y0jKGU4ojFLHqi3FtlTm004eLBC1aF3lAMVzSgx2HcQLUIecMgiAR8K4Qxm4QQbbZdY0 …
```
=> Onslaught movement speed fix

src/Classes/BuildListControl.lua
Closes https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/1823
Implements lua side code for https://github.com/PathOfBuildingCommunity/PathOfBuilding-SimpleGraphic/pull/63 allowing for deletion of folders with contents.
=> Implement ability to delete folders with contents

src/Modules/CalcPerform.lua
=> Fix Ingenuity belt not working with reflected rings from Kalandra's Touch

src/Modules/CalcOffence.lua
=> Add support for Grinning Immolation and Pain Attunement

src/Data/ModCache.lua, src/Modules/CalcDefence.lua, src/Modules/ModParser.lua
Fixes #424  .
Adds support for two modifiers:
Cannot have Energy Shield
Regenerate 0.05 Life per second per Maximum Energy Shield
=> Add support for Mask of The Stitched Demon

src/Modules/CalcOffence.lua
=> Fix Maligaro's Virtuosity Critical Damage Bonus calculation

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt
Fixes #470
Fixes #464
Add projectile flag to parts
<pre>eNrdW1lv4zgSfu78CkHAArtAJz4S54LTAyd2jkEOt510dp8ajETb3FCiW6KSeBb737eK1GW3KVPO285DWhbrq4usIquo6f7xEXDnjUYxE-GZ29prug4NPeGzcHrmPj1e7h67f3zb6Q6JnD1MzhPGcaT9bedLV_1wOH2j_Mw9cB2Pkzi-JwE9c0cknNLIdUjs0dC_KAbuRUhdR5JoSuWPTGjzZwvQMxIRT9LoFhn2EinuhA8IGSWACAgLx8J7pfIqEskcFHWdN0bfNc3N3fBh9OiCUl-6Q04WNBpLIp0Y_py5PTCOTGmfBPAXUIQnAGnu7R-1T5rH7Y7bqMSdJ1Esa4PHc0r9nL611zYRDiM6mEyoJ9kbvYiYvJiR0CskGQWsoW3uHVaS3yVcsjlnODEpxKjW9W_cW_sm2kchCe8PxyVFDg6ODo5PTqoRQhYIE-Uzk7NzDr6sxR9RN9OQSVobNhQsFuFW1iyBjBORcA4BZEU7ojGN3ohkKwoZeYvghYU1fdWLKHmY6DU4Ij5L4jsqIxqXFu-xCXtHQnIh4mIej9tVpEMaQTqQS4jmBsCYegIySBlycrx3YCFmPdgo75ZNqD1lLVNSQF1ttrNjMLalq814O4VGkDntKMci4ZaUsshhRyaiPv0oFnHHHGS_yoTtppHyJpSbhQK7Ml0Fuz59Exjam61VCWZwPSyF2V6z0zmEPajdOW63jHvLbBEzj_A78sGCJICc_kheaSGw1Tw0 …
=> Fix projectile scaling for Bonestorm and Gas Arrow

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt, src/Modules/ConfigOptions.lua
Does not implement the thorns damage yet
=> Add support for Armour Buff on Scavenged Plating

changelog.txt, spec/System/TestItemParse_spec.lua, src/Classes/PassiveTree.lua, src/Classes/SkillsTab.lua, src/Classes/TradeQueryGenerator.lua, src/Classes/TradeQueryRequests.lua, src/Data/ModCache.lua, src/Data/Uniques/ring.lua, src/Export/Main.lua, src/Export/Scripts/mods.lua, src/Export/Scripts/skillGemList.lua, src/Export/Uniques/ring.lua, src/Export/statdesc.lua, src/Modules/Build.lua, src/Modules/CalcSetup.lua, src/Modules/ItemTools.lua
=> fix spelling batch1

src/Export/Main.lua
Added button to clear script output in Dat View
- Tested feature in Dat View
- All tests successful
=> Add clear button in dat viewer

src/Classes/ItemsTab.lua, src/Classes/PassiveTreeView.lua, src/Data/Global.lua, src/Modules/CalcSetup.lua, src/Modules/Common.lua, src/Modules/ModParser.lua
Current live version of time-lost jewels slow down the app pretty bad depending on how many jewels and mods they have, There's an exponential issue that definitely needs to be addressed. This PR reworks the entire logic to pass every line through our parser, so we will parse any Small/Notable mod if we already parse what the mod "also grants". It then caches the mods for each jewel. On hover, the new mods are created into the line to be shown, may sound like a lot but these jewels can only add 4 so at most.. 7? mods on a node, give or take. So the data in the backend/calcs is good always, but technically the nodes don't show the right number until you observe it. Like quantum stuff :D 
This with a somewhat tight conditional to avoid processing the same node aggressively has dramatically …
=> Reduce performance issues with Time-Lost Jewels

.github/ISSUE_TEMPLATE/accuracy_bug_report.yaml, .github/ISSUE_TEMPLATE/application_bug_report.yaml, .github/ISSUE_TEMPLATE/behaviour_bug_report.yaml, .github/ISSUE_TEMPLATE/calculation_bug_report.yaml, .github/ISSUE_TEMPLATE/crash_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
Clarify which PoB edition this is for, and that we need a build code from PoB.
=> update issue templates

src/Data/ModCache.lua, src/Modules/CalcPerform.lua, src/Modules/ModParser.lua
Fixes #599
"From equipped shield" was only checking if the offhand wasn't empty, update parser to use UsingShield condition. Also added support for UsingFocus as it was unsupported and very easy to add alongside these changes.
<pre>eNrNW1tz4rgSfh5-hYuqU7VbS4JtMDYpsluQkMtMLiwkmTPnZUuxBWgRNmPLSZhT-99PS7KNYZCxk5ezDxlj9ddSX9Tqbnl7f7wtqfaCw4gE_mndONbrGvbdwCP-7LT--HBx5NT_-L3WGyE2v58OYkL5iPl77VNP_NAofsH0tG5265pLURTdoSU-rY-RP8NhXUORi33vbDNwF_i4rjEUzjB7SmfV_zIAPUchchkObzjHfsyC28ADBAtjQCwR8SeBu8DsMgziFay0rr0Q_Cpprm9H9-OHOqzqU29E0RqHE4aYFsGf03ofpEMzfI6W8BdQiMYA0Y_1rllvFkIGcRixKrjJCmMvIzWOlYSjEA-nU-wy8oLPQsLO5sh3c5OocFVpb2PKyIoSbouEXrmmq59Ymy0V7UPAED0fTXJqMQy9XUwesMOL_krYfEBBi-WZc8j1zCcMV8OMAhIFfnUhthBK5ceUwkYpRTvGEQ5fECM7q1HyDpbPxK-iolvko7MgKqF_TjnCIexaVgkwwW4AG73qHBWRN2SKy1NWkiMBVF3N--QYTsrSVWb8vgWN …
=> Fix "from Equipped Shield" and add support for "from Equipped Focus"

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
The effect on the buffs had a effect condition which wasn't needed and was causing issues
Fixes #652
=> Fix Charge Infusion not working sometimes

src/Data/SkillStatMap.lua, src/Data/Skills/other.lua, src/Export/Skills/other.txt, src/Modules/CalcActiveSkill.lua, src/Modules/CalcOffence.lua
Fixes #441  
Attempt number 2 at scaling Concoction skills as Unarmed. First PR used a flag and checked the skillModList which only kinda worked or basically didn't at all once it got to live, this PR adds the tag/distinction directly onto the skills. If the skill exists, it has the tag and we can use it. Also fixed an issue from last PR where I forgot to clear the source of the offhand weapon in the case of dual wielding.
- Build should scale with Unarmed, Projectile, Attack
- Build should not scale with anything Weapon-related
- Build should continue not to scale Melee
- Crit and Attack Speed should be locked to 0% base and 1.2 base respectively
Some FYI with damage differences, Coming Calamity does not apply if you are unarmed because I guess Heralds don't count as active without a …
=> Fix Concoction skills not being treated as Unarmed

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt
The palm skills deal unarmed damage for a part of their skill
=> Fix Palm skills not scaling with unarmed damage

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
The skill is a shield attack
Fixes #324
=> Fix Magma Barrier damage calculation

src/Data/SkillStatMap.lua, src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt
Both skills scale with non weapon attack damage
=> Fix Voltaic Nova and Freezing Nova damage scaling

src/Data/Skills/act_dex.lua, src/Export/Skills/act_dex.txt
=> Fix Herald of Thunder not using weapon damage

src/Data/SkillStatMap.lua, src/Modules/CalcOffence.lua
Fixes #684 
Adds support for the additional second added to Comet's total cast time.
<pre>eNrtPWlz2ziyn0e_guWqefW2rNgEePvZs-Uz8cSHxnKSmfmSgilIYkyRCg8f2Zr__roBUiIlkqLknV3PkQ-ORHQ3gO5GH0AT2v_n08RXHngUe2FwsEV21C2FB2448ILRwdaH27M39tY_f-js91gyvh4epZ6PLfSHznf74ovi8wfuH2w5gOf6LI6v2IQfbPXDyOURj-MthcUuDwbHhbYkjCaPnEGnW0rCohFPPub9q58J0BmziLkJjy6Q9mGahJfhABCTKOVbyoR5QT9073nyNgrTKYx5S3nw-KOEOb_sXd_cbsH4vtvv-eyZR_2EJUoMfw62DqFLNuLvvARQmJ8CvOGohrFjWpq5tduIdJRGcXLCJvBxDeT-lPPBDJ7uGEYdZC_ip8MhdxPvgR9HXnI8ZoE774rQOsS1gS9TP_GmvofszxC0HZ3UobxbJq-qdcC3YcL8k15_DmuohkN2HNMy7WakcC4UdRVksYda4OPU90FXW8He8JhHDywBJWxHO5zceQEfHD6M1lGliLProRTzDRt4aXzJE1glBQWpZdIlC9hxGBc019SbYHscVmCQlFDUFQh97oawVIsoRNfsHdqio2r02h4vvCFvD7nWZDKEdUez2TxO-23h1ia82YBuwEC1g-yHqd8SMpmbCqMW6oQ_zaFqVeY8mHdIHa1-QX4tQapGfbcPIa7bltbj9F2voNy6Zu1QR7 …
=> Add support for +Total Cast Time on Comet's and Lightning Conduit

src/Data/ModCache.lua, src/Modules/ModParser.lua
Just added Earthquake to release version and compared values.
=> Added Support for "Slam skills have +% increased Area of Effect"

src/Data/SkillStatMap.lua
Partially fixes #823  .
Overwhelming presence is not supported. This pr add support for the ailment threshold part
- enable/disable overwhelimg presence and check shock chance in calc tab
[test build](eNrVW21v4zYS_rz-FYKBAnc4J7bk1wROC-dt4yJOvHaye_1UMBJtq6FFV6KSuMX-95shJUv2mjKV4HC4fujK4jzD4QxnODNU-r-8LZn1QsPI58FZ1T5uVC0auNzzg_lZ9fHh-qhX_eXnSn9MxOJ-dh77DEecnyuf-vKHxegLZWdVB3AuI1F0R5b0rDriwXPVIpFLA-8ie33HA1q1BAnnVHxN52z8bgN2QULiChreIr9BLPiIe4AQYQyIJfGDKXefqfgc8ngF01WtF5--KprhaHw_eaiCTJ_6Y0bWNJwKIqwI_ndWHcDayJze-AIghMVA36jWC2nP4zASl2QJj4cx0xWl3oYM9NfUUV6EvhjFTPgr5tNwA3F09CDyxYIEbiaE3dCK8cAFYZfj6WGBFSU3UMc3XyzOGSzPiC9SD-eBL6gx-Zj7EQ9KSW1EfBEzBrvUiHZCIxq-EOEbCnLBl09-YKiTEQnIBY-EGeWYhuAvohRgSl0OLlZ2jpLIW39GzSlLrSMBlJXmfeu4mprSlWb8PoEmEGPMKKc8ZoaUIsxFjKZ-4_-Zp-xpCS_pW8av6xTw26LstHWUw0DkBOwWMMxTdlp …
=> support ailment part of overwhelming presence skill

src/Modules/ConfigOptions.lua
- Only show is enemy X when there is condition
- Only show stack counter if there is XCanStack
=> Only show bleed/ignite/poison options when needed

src/Data/Skills/sup_dex.lua, src/Export/Skills/sup_dex.txt
Just a bit sized PR so we don't overlap work.
=> Add support for Excoriate and Adhere

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Data/Skills/other.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt, src/Export/Skills/act_str.txt, src/Export/Skills/other.txt
Many skills were missing the projectile scaling on them
Some other were scaling with area damage when they shouldn't be
=> Fix Area and Projectile flags for many skills

CHANGELOG.md, changelog.txt
=> fix: spelling

src/Classes/GemSelectControl.lua, src/Classes/SkillsTab.lua, src/Modules/CalcTools.lua
Some support gems have more than 1 level for some reason
Fixes #895
=> Fix some support gems showing a stat requirement

src/Data/ModCache.lua, src/Modules/ModParser.lua
=> Add support for Infernalist's "Bringer of Flame" ascendancy

src/Classes/ImportTab.lua
Fixes #892
This PR allow to parce grantedSkills from api response
=> Fix Import for skills granted by items

src/Data/Uniques/Special/Generated.lua, src/Data/Uniques/amulet.lua, src/Data/Uniques/belt.lua, src/Data/Uniques/body.lua, src/Data/Uniques/boots.lua, src/Data/Uniques/flask.lua, src/Data/Uniques/focus.lua, src/Data/Uniques/gloves.lua, src/Data/Uniques/helmet.lua, src/Data/Uniques/jewel.lua, src/Data/Uniques/mace.lua, src/Data/Uniques/quiver.lua, src/Data/Uniques/sceptre.lua, src/Data/Uniques/shield.lua, src/Data/Uniques/staff.lua, src/Export/Uniques/amulet.lua, src/Export/Uniques/belt.lua, src/Export/Uniques/body.lua, src/Export/Uniques/boots.lua, src/Export/Uniques/flask.lua, src/Export/Uniques/focus.lua, src/Export/Uniques/gloves.lua, src/Export/Uniques/helmet.lua, src/Export/Uniques/jewel.lua, src/Export/Uniques/mace.lua, src/Export/Uniques/quiver.lua, src/Export/Uniques/sceptre.lua, src/Export/Uniques/shield.lua, src/Export/Uniques/staff.lua
Just some more uniques from Poedb and trade. Also fixed The Coming Calamity to have variable herald level.
- Death Articulated
- Hyrri's Ire
- Rathpith Globe
- The Gnashing Sash
=> Add 4 More Uniques

src/Modules/CalcDefence.lua, src/Modules/CalcOffence.lua
The Ailment chance mods were not being taken into account for calcs
Fixes #923
=> Fix "increased Ailment chance" mods not working

src/Data/ModCache.lua, src/Modules/CalcOffence.lua, src/Modules/ModParser.lua
Also fixes the handling of Amazon's Mystic Harvest node as that was not working at all before
=> Add support for Acolyte of Chayula's Ravenous Doubts node

src/Modules/CalcSetup.lua, src/Modules/ModParser.lua
Adds handling for the following mods:
- `+2 to Level of all Skills with an Intelligence requirement`
- `+2 to Level of all Skills with a Dexterity requirement`
- `+2 to Level of all Skills with a Strength requirement`
- Verify using the test build below 
```
eNqtW11X2zwSvm5_hU8u9ma35BvCu6HvCQkUzoGSTaDdveoRtpJoka3UkoG8v35nJH8FIkcO24vWseaZ0Yw0o5mRO_zzNeTeM40lE9FZo33Uang08kXAouVZ4-H-8sug8efXz8MpUau7xXnCOI50vn7-NNQ_PE6fKQdgw_M5kfI7CelZY0aiJY0bHpE-jYJxMfBdRLThKRIvqfqRCW39QvSKxMRXNL5BhqNEiVsRAELFCSBCwqK58J-o-haLZK3lPTP6Ymiub6d3s_sGTOrTcMrJhsZzRZQn4a-zxgiUI0t6xRRACE-A_rh3cnTSbbdP-o1mJeg8iaWakBAea4Dna0qDnL511Bl0O63-4LR1POj0uzbUNKYXiwX1FXum45ip8YpEfiG2bQXWJr5NuGJrznCFUkDnaGCFXL1n32rZiO-FInwynRe0g-5Rr9fuDHrd7uCkXY0TxRpZJfxkanXOwcIHSEHs9TJiih4IngomRfQB_cpQq4rjhHPwMifaGZU0fiaKbU_LzluEjyw6yHpjIXggXqIc1 …
```
=> Add handling for +2 to Level of all Skills with a X requirement

src/Modules/CalcDefence.lua
PoB2 equivalent of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8594
Notably this highlights that in PoE2 chaos deals double damage against ES
=> Add resource lost information to enemy damage breakdown

src/Data/ModCache.lua, src/Modules/ModParser.lua
Supports all but 3 of the Smith's Masterwork nodes. Requires Normal Body Armour equipped.
~~Unfixed, separate solution needed:
Armour to Chaos Hits
Unaffected by Ignite
Hits against you have 50% reduced Crit Damage Bonus~~
<pre>eNrtW1tz4joSfh5-hYuqU7Vbm4sxmEuKnC1CkknOyYUDuezsy5RiBGgiLI4tJ2G29r9vt2QbSJAjJ_uwDzszlQGrv1ar1d3qbjndv7_MufNEo5iJ8LBa23OrDg0DMWbh9LB6e3O6267-_ddKd0Dk7HpylDCOI96vlS9d9cXh9IlyAPpVJ-Akjq_InB5W70kUMRFVHRIHNBz3VyOjOZMzR0yc35kkT6TqSBJNqbzLJHC_14DTjEQkkDS6QO69RIpLMQawjBJadeaEhSMRPFL5NRLJAiavOk-MPmua88vB9fCmChJ-6Q44WdJoJIl0YvhxWO3BSsmUHpM5_AQU4QlA3L2a61f3CyFHSRTLMrjRgtJxTlrba5gIBxE9mUxoINkT7UdM9mckDNYmMeHK0l4mXLIFZzTK6T0T_dkb1jUj7Y2QhB8PRutqabSKqYV8X-Z7MJQjDkq05o2I82nIJC0FGQgWi7D0CjYARsUnnIPDWNEOaUyjJyLZK2GMvMX8gYUl9HNJQtIXsYXukXJAI_BdWQowooEAdy87R0nkBZtQe8pS60gBZaX52DpORrZ0 …
=> Add support for most Smith's Masterwork mods

src/Data/SkillStatMap.lua, src/Modules/CalcOffence.lua
The mods on the skills were incorrect and they were not using the crit chance stat from the skill
Fixes #998
Fixes #995
=> Fix Concoction skill Crit Chance and base damage

src/Data/ModCache.lua, src/Modules/ModParser.lua
- "Add support for "leech from critical hits is instant"
- Mod gets parsed correctly
- Leech in general is not fully supported for PoE2 mechanics yet and "instant" leech does not really have any effect for now
=> Add support for Atziri's Acuity (Unique Gloves)

src/Data/ModCache.lua, src/Modules/ModParser.lua
- Add support for "Critical hits Poison the enemy"
=> Add support for Atsak's Sight (Unique Helmet)

src/Classes/ImportTab.lua
=> POE Api: Logout from api

src/Modules/CalcSections.lua
=> Show Quiver Effect breakdown on Calcs Tab

src/Data/Skills/act_int.lua, src/Export/Skills/act_int.txt, src/Modules/CalcDefence.lua, src/Modules/CalcSections.lua
The Discipline value granted by the Aura is not scaled by any of the mods on the player
Fixes #1072
=> Fix Discipline value being scaled by mods

src/Classes/ItemsTab.lua, src/Modules/CalcPerform.lua
Same fix from PoB 1 https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8610
Also applies to charms for PoE 2 and the Lich jewel socket in-case PoE 2 ever adds relic items
=> Fix some Relic items not counting as Unique

src/Modules/CalcDefence.lua
Copy of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8607
=> Change wording for "Base Damage Reduction" on Hit taken mult. section

src/Modules/CalcPerform.lua
Copy from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8814
=> Sort Attribute Requirement List

src/Modules/CalcDefence.lua, src/Modules/CalcPerform.lua
Copy from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8783
=> Fix Reduced Effect of Curses on Self not clamping

src/Classes/GemSelectControl.lua
Copy from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8802
=> Fix gems being added to skill groups when sorting dropdown

src/Classes/ItemDBControl.lua
Copy from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8803
=> Fix Item sort option for "Current Usable" not using taking into account attribute requirement mods

src/Modules/CalcDefence.lua
Copy from https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8711
=> Fixed EHP based on block effect calculation

src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Data/Skills/minion.lua, src/Data/Skills/other.lua, src/Data/Skills/spectre.lua, src/Export/Scripts/skills.lua, src/Modules/CalcTools.lua, src/Modules/CalcTriggers.lua, src/Modules/Data.lua
Copy of https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8719
Fixed it to use statSets in PoB 2
Also added a check on export to not add duplicate stats
=> Fix minion skill type issues causing mod compatiblity issues

src/Data/Minions.lua
=> Fix crash when allocating Answered Call

src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Export/Skills/act_int.txt, src/Export/Skills/act_str.txt
Fixes #1288 .
Herald of Blood didn't have a mod applying that actually triggered the "AffectedBy" condition.  This PR adds the same behavior as Herald of Ice now.
- Use the build provided in the linked issue, verify it now has 40% increased physical damage
```bash
eNrVG9tu27jyuf4KwcA-rRNL8jWB04Vza9xNGq-dtLtPBSPRNhtKciUqiYv9-DNDSrLsWDKVHBzg9CGVyLmQM8O5UR788eJx44mGEQv8k7p1aNYN6juBy_z5Sf3-7vKgX__jY20wJmJxOzuNGccZ-2Ptw0C-GJw-UQ6IvbrhcBJFX4hHT-o3gf9YN0jkUN89Ww-P_KfgkYZ1Q5BwTsXXlK353QL0BQmJI2h4jSSHsQhuAheQRBjTuuER5k8D55GKT2EQL4Fj3Xhi9FnBjG7Gt5O7Oizrw2DMyYqGU0GEEcGfk_oQtkfm9IoJQCE8Bniz3iyFPY3DSJwTDx7340yXlLoZmFUENg7pxWxGHcGe6FnIxNmC-I4G-aqwNzEXbMkZyjmBt4vgr16RtsxC4neBIPx8PN2_DAUZaMj7GxOLUw7y06KL0KO5zwTVBh8HLAr8SqvWAj6LOYeToAU7oRENn4hgmgs5C7wH5mvK5Ib45CyIhB7kmIZwJkUlhCl1AjjGVXlUxLxmM6oPWWkfCULV1bx …
```
=> Fix Herald of Blood buff not applying for conditional mods

src/Data/Skills/act_str.lua, src/Export/Skills/act_str.txt
The skill didn't have the attack tag on it
=> Fix Requiem not showing damage values

src/Data/Uniques/helmet.lua, src/Export/Uniques/helmet.lua
Fixes #1311 
The new mod here was undocumented in the patch notes
=> Update Constricting Command unique helmet mod

src/Classes/TradeQueryGenerator.lua, src/Data/QueryMods.lua
Fixes #1367 .
GGG added pseudo mods to https://www.pathofexile.com/api/trade2/data/stats which shifted all of the indices.  I'm not 100% familiar with this process, but am trusting the scripts to do their thing
=> Fix trade search for Megalomaniac

src/Modules/CalcOffence.lua
Forgot to take the inverse of the time when applying it in the formula
=> Fix Channel Time on Incinerate

src/Data/ModCache.lua, src/Modules/ModParser.lua
Didn't test the cost efficiency in game, assume it should be right though.
=> Add support for Primed to Explode and Price of Freedom

src/Data/ModCache.lua, src/Modules/ModParser.lua
Quick parsing of Bolt Speed on the unique Rampart Raptor
=> Add support for Bolt Speed

src/Modules/ConfigOptions.lua
=> Make unset quest rewards more visible

src/Data/SkillStatMap.lua, src/Data/Skills/act_dex.lua, src/Data/Skills/act_int.lua, src/Data/Skills/act_str.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/act_int.txt, src/Export/Skills/act_str.txt
Snap
Elemental Sundering
Boneshatter
Fragmentation Rounds
Also fixes the missing More Physical damage mod on Frag rounds
=> Add damage against Uniques on some skill gems

src/Data/Skills/sup_dex.lua, src/Export/Skills/act_dex.txt, src/Export/Skills/sup_dex.txt
Simple support gem to add support for
=> Add support for Rigwald's Ferocity
